begin;

insert into public.grupos (id, nombre)
overriding system value
values
  (1, 'The Beatles'),
  (2, 'The Rolling Stones'),
  (3, 'Tom Petty & The Heart Breakers'),
  (4, 'Tom Petty'),
  (5, 'Traveling Wilburys'),
  (6, 'Corey Harris'),
  (7, 'Pearl Jam'),
  (8, 'Eric Clapton'),
  (9, 'The Who'),
  (10, 'Led Zeppelin'),
  (11, 'AC/DC'),
  (12, 'Adele'),
  (13, 'Aerosmith'),
  (14, 'Alice in chains'),
  (15, 'Amy Winehouse'),
  (16, 'Anne MacCue'),
  (17, 'Ariel Rot'),
  (18, 'Jackie Brown'),
  (19, 'Beastie Boys'),
  (20, 'Ben Harper'),
  (21, 'Bob Dylan'),
  (22, 'Bruce Springsteen'),
  (23, 'Bulldozer'),
  (24, 'Dexter Gordon'),
  (25, 'Miles Davis'),
  (26, 'Sonny Rollins'),
  (27, 'Kenny Burrell'),
  (28, 'Thelonious Monk'),
  (29, 'Joe Henderson'),
  (30, 'Cannonball Adderley'),
  (31, 'Charlie Parker'),
  (32, 'Chick Corea'),
  (33, 'Bill Evans'),
  (34, 'Pablo Almaraz'),
  (35, 'Weevers'),
  (36, 'High Felicity'),
  (37, 'Roy Orbison'),
  (38, 'Surfin'' Bichos'),
  (39, 'Tom Jones'),
  (40, 'Art Blakey and the Jazz Messengers'),
  (41, 'Herbie Hancock'),
  (42, 'Duke Ellington'),
  (43, 'Wayne Shorter'),
  (44, 'Horace Silver'),
  (45, 'Lee Morgan'),
  (46, 'John Coltrane'),
  (47, 'Caetano Veloso y Gilberto Gil'),
  (48, 'Jimmy Smith'),
  (49, 'Billie Holiday'),
  (50, 'Chez Luna'),
  (51, 'Coldplay'),
  (52, 'Collective Soul'),
  (53, 'Cream'),
  (54, 'Dave Matthews Band'),
  (55, 'Deep Purple'),
  (56, 'Delamitri'),
  (57, 'Diana Krall'),
  (58, 'Dire Straits'),
  (59, 'Dream Theater'),
  (60, 'Eleanor McEvoy'),
  (61, 'Elvis Presley'),
  (62, 'Everlast'),
  (63, 'Faith No More'),
  (64, 'Frank Sinatra'),
  (65, 'Frank Zappa'),
  (66, 'Fumanchu'),
  (67, 'Funkadelic'),
  (68, 'Gari'),
  (69, 'Gary Moore'),
  (70, 'Gerry Rafferty'),
  (71, 'Gov''t Mule'),
  (72, 'Guns N'' Roses'),
  (73, 'Hiram Bullock'),
  (74, 'Jeff Buckley'),
  (75, 'Jethro Tull'),
  (76, 'Jimi Hendrix'),
  (77, 'Jimmy Page & The Black Crowes'),
  (78, 'Joe Satriani'),
  (79, 'John Mayall & The Blues Breakers'),
  (80, 'John Mayer'),
  (81, 'John McLaughlin, Al di Meola, Paco de Lucia'),
  (82, 'Keane'),
  (83, 'Keith Richards'),
  (84, 'Kerri Chandler'),
  (85, 'Kid Rock'),
  (86, 'Kiss'),
  (87, 'KT Tunstall'),
  (88, 'Kukuma'),
  (89, 'Lenny Kravitz'),
  (90, 'Lighthouse Family'),
  (91, 'Live'),
  (92, 'Lizz Wright'),
  (93, 'Lou Reed'),
  (94, 'Louis Amstrong'),
  (95, 'Luar Na Lubre'),
  (96, 'Lynch Mob'),
  (97, 'Lynrd Skynyrd'),
  (98, 'Maceo Parker'),
  (99, 'Macy Gray'),
  (100, 'Marah'),
  (101, 'Marvin Gaye'),
  (102, 'Mauri Sanchis'),
  (103, 'Metallica'),
  (104, 'Mi Hermana Corina'),
  (105, 'Michael Jackson'),
  (106, 'Miguel Salvador'),
  (107, 'Mike Oldfield'),
  (108, 'Mojo Project'),
  (109, 'Morcheeba'),
  (110, 'Neil Young'),
  (111, 'Ocean Colour Scene'),
  (112, 'O''funkillo'),
  (113, 'Paco de Lucia'),
  (114, 'Pink Floyd'),
  (115, 'Primus'),
  (116, 'Prince'),
  (117, 'Queens of the stone age'),
  (118, 'Rage Against The Machine'),
  (119, 'Red Hot Chili Peppers'),
  (120, 'Robben Ford'),
  (121, 'Robert Johnson'),
  (122, 'Ronny Jordan'),
  (123, 'Ry Cooder'),
  (124, 'Ryan Adams'),
  (125, 'Sex Pistols'),
  (126, 'Staind'),
  (127, 'Steve Vai'),
  (128, 'Stevie Ray Vaughan'),
  (129, 'The Black Crowes'),
  (130, 'The Clash'),
  (131, 'The Cult'),
  (132, 'The Meters'),
  (133, 'The Police'),
  (134, 'The Pretenders'),
  (135, 'The Screamin´ Cheetah Wheelies'),
  (136, 'The Verve'),
  (137, 'Tom Waits'),
  (138, 'Train'),
  (139, 'U2'),
  (140, 'US3'),
  (141, 'Van Halen'),
  (142, 'Varios'),
  (143, 'Whitesnake'),
  (144, 'Wolfmother'),
  (145, 'WOP'),
  (146, 'ZZ Top'),
  (147, 'Soda Stereo'),
  (148, 'The Velvet Underground & Nico'),
  (149, 'Muse'),
  (150, 'Simply Red'),
  (151, 'Niña Pastori'),
  (152, 'Sade'),
  (153, 'Rojo Nieve'),
  (154, 'Sound Garden'),
  (155, 'Antonio Orozco')
on conflict (id) do update
set nombre = excluded.nombre;

select setval(
  pg_get_serial_sequence('public.grupos', 'id'),
  coalesce((select max(id) from public.grupos), 1),
  true
);

commit;
