begin;

with source (
  ord,
  imagen,
  enlace,
  texto,
  categoria,
  plataforma,
  info
) as (
  values
  (1, 'soundbreaking.jpg'::text, 'https://caixaforumplus.org/v/soy-mi-musica'::text, 'Soundbreaking'::text, 'Mix'::text, 'caixaForum'::text, null::text),
  (2, 'janis_little_girl_blue.jpg'::text, 'https://caixaforumplus.org/v/janis-little-girl-blue'::text, 'Janis Joplin'::text, 'Mix'::text, 'caixaForum'::text, null::text),
  (3, '27_gone_too_soon.jpg'::text, 'https://www.netflix.com/es/title/80176322?s=a&trkid=13747225&trg=more&vlang=es&clip=81494645'::text, '27: Gone Too Soon'::text, 'Mix'::text, 'netflix'::text, null::text),
  (4, 'bowie_the_man_who_changed_the_world.jpg'::text, 'https://www.netflix.com/es/title/80176322?s=a&trkid=13747225&trg=more&vlang=es&clip=81494645'::text, 'Bowie'::text, 'Mix'::text, 'netflix'::text, null::text),
  (5, 'rolling_thunder_review.jpg'::text, 'https://www.netflix.com/es/title/80221016?s=a&trkid=13747225&trg=more&vlang=es&clip=81022982'::text, 'Rolling Thunder Revue'::text, 'Mix'::text, 'netflix'::text, null::text),
  (6, 'i_dream_of_wires.jpg'::text, 'https://caixaforumplus.org/v/i-dream-of-wires'::text, 'I Dream of Wires'::text, 'Mix'::text, 'caixaForum'::text, null::text),
  (7, 'volver_a_ser_un_niño.jpg'::text, 'https://play.rtve.es/v/6182863'::text, 'Volver a ser un niño'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (8, 'cruce_de_caminos.jpg'::text, 'https://play.rtve.es/v/6905202'::text, 'Cruce de caminos'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (9, 'tiempo_de_leyenda.jpg'::text, 'https://play.rtve.es/v/6638540'::text, 'Camarón de la Isla'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (10, 'paco_de_lucia.jpg'::text, 'https://play.rtve.es/v/2418425'::text, 'Paco de Lucía'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (11, 'freddie_mercury.jpeg'::text, 'https://play.rtve.es/v/6918647'::text, 'El último acto'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (12, 'antonio_vega.jpeg'::text, 'https://www.Filmin.es/pelicula/antonio-vega-tu-voz-entre-otras-mil'::text, 'Antonio Vega'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (13, 'ecos_de_una_era.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjSp7HMxp6CAxXXQaQEHa5zCVQQtwJ6BAgMEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fecos-de-una-era%2Fumc.cmc.4hppqw2jahbin2l48gd9f16nf&usg=AOvVaw2hrT9bIGuWM8J9Y-ygel24&opi=89978449'::text, 'Ecos de una era'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (14, 'amy.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwirhJHGx56CAxVodqQEHUMDDsUQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Famy%2Fumc.cmc.2jhzj3f3ic3shrf0gt5450j9z&usg=AOvVaw0fqxOJT-sdFRz2XaG6qI54&opi=89978449'::text, 'Amy'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (15, 'recuperar_a_amy.jpeg'::text, 'https://play.rtve.es/v/6752148'::text, 'Amy'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (16, 'jimi_hendrix.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjRxv-1yJ6CAxWZTaQEHTlsA38QFnoECBAQAQ&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fjimi-hendrix%2Fumc.cmc.2ejhgak5s3zf2i5u8qb2eyx6y&usg=AOvVaw376uQo1FcnIAnCntb3wQxF&opi=89978449'::text, 'Jimi Hendrix'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (17, 'michael_jackson.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiris-UyZ6CAxXKVKQEHWlaDQ8QtwJ6BAgJEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fmichael-jacksons-journey-from-motown-to-off-the-wall%2Fumc.cmc.1yty35824fahqfym1x9f6beyl&usg=AOvVaw1G8js4VZfnRWDtH2j7H5FR&opi=89978449'::text, 'Michael Jackson'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (18, 'neil_young.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwirtObWyZ6CAxUTfqQEHSQ4A-QQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fneil-young-journeys%2Fumc.cmc.1s6tv7posl29tolicf7blrp8m&usg=AOvVaw1MlLpchszZ_PwZ5Db0BbOW&opi=89978449'::text, 'Neil Young'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (19, 'oasis.jpeg'::text, 'https://www.youtube.com/playlist?list=PLnnFvexl8Ac6AZUFcxdvI-GAXE_C1R_Hz'::text, 'Oasis'::text, 'Mix'::text, 'youtube'::text, null::text),
  (20, 'jeff_beck.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjB2bisy56CAxUZRaQEHbiJAwkQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fthe-jeff-beck-story-still-on-the-run%2Fumc.cmc.4hm4bx0m62ids7p0olfy6k7zv&usg=AOvVaw3Kn2BWy4auWq-iar5fEKPY&opi=89978449'::text, 'Story'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (21, 'jeff_beck_live.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiI2q31zp6CAxWdV6QEHZjWDUQQtwJ6BAgMEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fjeff-beck---live-in-tokyo%2Fumc.cmc.4z8wk1t9y1hbvuucp552rttdi%3Fl%3Des&usg=AOvVaw2WaJyFRpCCkyUM6NItVS6y&opi=89978449'::text, 'Live in Tokyo'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (22, 'kurt_cobain.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwibvoTHz56CAxUhUKQEHXbCB9IQtwJ6BAgPEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fcobain-montage-of-heck%2Fumc.cmc.6kfpwg3avmrvuv16w8gosungr&usg=AOvVaw38sAXse3qgeu69cVtZBST1&opi=89978449'::text, 'Kurt Cobain'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (23, 'lambert_stamp.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwil8vm90J6CAxX7UKQEHTptDPsQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Flambert--stamp%2Fumc.cmc.c9efy5r7rx7n2d8l7uyvp0ly%3Fl%3Des&usg=AOvVaw2PFh8O48b4OkZHJDAO8J0N&opi=89978449'::text, 'Lambert & Stamp'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (24, 'acdc_live.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiFn5j40J6CAxUnVKQEHT85AXUQtwJ6BAgNEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Facdc-live-at-river-plate%2Fumc.cmc.4eol4augqp3w8wkzieg180jj5&usg=AOvVaw0BkvM28HSUHT16aDQ3LlFZ&opi=89978449'::text, 'AC/DC'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (25, 'miles_ahead.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjaq46F0p6CAxUEVKQEHQ2MDA0QtwJ6BAgPEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fmiles-ahead%2Fumc.cmc.5u572pown4kesqnhhjd0u3hgg&usg=AOvVaw0ZJA9B2Yg3iWWuXnaskGiu&opi=89978449'::text, 'Miles Ahead'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (26, '35.jpg'::text, 'https://www.netflix.com/es/title/80227122'::text, 'Miles Davis'::text, 'Mix'::text, 'netflix'::text, null::text),
  (27, 'all_my_loving.jpg'::text, 'https://www.netflix.com/es/title/70076332?s=a&trkid=13747225&trg=more&vlang=es&clip=81597056'::text, 'All My Loving'::text, 'Mix'::text, 'netflix'::text, null::text),
  (28, 'hiphop.jpeg'::text, 'https://www.netflix.com/es/title/80141782?s=a&trkid=13747225&trg=more&vlang=es&clip=81015553'::text, 'Hip-Hop Evolution'::text, 'Mix'::text, 'netflix'::text, null::text),
  (29, 'bob_marley.jpeg'::text, 'https://www.netflix.com/es/title/80191047?s=a&trkid=13747225&trg=more&vlang=es&clip=81024734'::text, 'Bob Marley'::text, 'Mix'::text, 'netflix'::text, null::text),
  (30, 'madonna.jpeg'::text, 'https://play.rtve.es/v/6998986'::text, 'Madonna'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (31, 'jagged.jpeg'::text, 'https://play.hbomax.com/page/urn:hbo:page:GYZYH-QhGxo3DaAEAAABO:type:episode'::text, 'Alanis Morissette'::text, 'Mix'::text, 'hbo'::text, null::text),
  (32, 'sugar_man.jpeg'::text, 'https://play.rtve.es/v/6752174'::text, 'Sugar Man'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (33, 'suecia.jpeg'::text, 'https://play.rtve.es/v/3640360'::text, 'Suecia'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (34, 'pj_harvey.jpg'::text, 'https://caixaforumplus.org/v/pj-harvey-a-dog-called-money'::text, 'PJ Harvey'::text, 'Mix'::text, 'caixaForum'::text, null::text),
  (35, 'jeff_buckley.jpg'::text, 'https://www.youtube.com/watch?v=CdnisUnJHIE'::text, 'Jeff Buckley'::text, 'Mix'::text, 'youtube'::text, null::text),
  (36, 'hit_so_hard.jpg'::text, 'https://www.Filmin.es/pelicula/hit-so-hard'::text, 'The Hole'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (37, 'control.jpg'::text, 'https://www.Filmin.es/pelicula/control'::text, 'Joy Division'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (38, 'white_riot.jpg'::text, 'https://www.Filmin.es/pelicula/white-riot-rock-contra-el-racismo'::text, 'AntiRacismo'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (39, '1.jpeg'::text, 'https://watch.plex.tv/es/movie/tom-petty-and-the-heartbreakers-runnin-down-a-dream'::text, 'Tom Petty Runnin` Down a Dream'::text, 'Mix'::text, 'plex'::text, null::text),
  (40, '2.jpeg'::text, 'https://www.canalsurmas.es/videos/54753-documentales-the-storm-jesus-poncesi-sat-ip-02092022'::text, 'Storm'::text, 'Mix'::text, 'canalsurmas'::text, null::text),
  (41, '3.jpeg'::text, 'https://www.Filmin.es/pelicula/crock-of-gold-bebiendo-con-shane-macgowan?shem=ssusxt'::text, 'Shane MacGowan'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (42, '5.jpeg'::text, 'https://www.amazon.com/-/es/Mick-Rock/dp/B06XYQKRBC'::text, 'Mick Rock'::text, 'Mix'::text, 'primevideo'::text, null::text),
  (43, '6.jpeg'::text, 'https://www.youtube.com/watch?v=QCgMgUcXxHs'::text, 'En la cama con Madonna'::text, 'Mix'::text, 'youtube'::text, null::text),
  (44, '7.jpeg'::text, 'https://www.netflix.com/title/81506634'::text, 'Ramoncín'::text, 'Mix'::text, 'netflix'::text, null::text),
  (45, '11.jpeg'::text, 'https://www.Filmin.es/pelicula/i-need-a-dodge-joe-strummer-on-the-run'::text, 'Joe Strummer'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (46, '12.jpeg'::text, 'https://www.Filmin.es/pelicula/dentro-del-chelsea-hotel'::text, 'Chelsea Hotel'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (47, '13.jpeg'::text, 'https://www.netflix.com/watch/81393720?trackId=255824129&tctx=0%2C0%2C69e99661-4f11-4a9e-8fba-26c7bc1f9e50-229969214%2C69e99661-4f11-4a9e-8fba-26c7bc1f9e50-229969214%7C2%2Cunknown%2C%2C%2CtitlesResults%2C81393720%2CVideo%3A81393720%2CminiDpPlayButton'::text, 'Heroes del silencio'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (48, '16.jpeg'::text, 'https://www.primevideo.com/detail/Mi-vida-entre-las-hormigas/0N0GLK8VCJES4ZUO2RAG6W20LV'::text, 'Ilegales'::text, 'Mix'::text, 'primevideo'::text, null::text),
  (49, '17.jpeg'::text, 'https://www.canalsurmas.es/videos/68602-ok-la-importancia-de-llamarse-ernesto-trailer-2022mp4-07032023/'::text, 'Eric Jimenez'::text, 'Mix'::text, 'canalsurmas'::text, null::text),
  (50, '27.jpeg'::text, 'https://www.youtube.com/watch?v=adTmmDA9jtk'::text, 'Camaron en Montreaux'::text, 'Mix'::text, 'youtube'::text, null::text),
  (51, '28.jpg'::text, 'https://www.netflix.com/title/81383233'::text, 'Bee Gees'::text, 'Mix'::text, 'netflix'::text, null::text),
  (52, '29.jpg'::text, 'https://www.netflix.com/title/81720500'::text, 'La Gran Noche del Pop'::text, 'Mix'::text, 'netflix'::text, null::text),
  (53, '33.jpg'::text, 'https://www.netflix.com/es/title/70308063'::text, 'Nina Simone'::text, 'Mix'::text, 'netflix'::text, null::text),
  (54, '34.jpg'::text, 'https://www.netflix.com/es/title/81428525'::text, 'Tina Turner'::text, 'Mix'::text, 'netflix'::text, null::text),
  (55, '36.jpg'::text, 'https://www.netflix.com/es/title/81469511'::text, 'Stamping Ground'::text, 'Mix'::text, 'netflix'::text, null::text),
  (56, '37.jpg'::text, 'https://www.netflix.com/es/title/81555066'::text, 'Beethoven'::text, 'Mix'::text, 'netflix'::text, null::text),
  (57, '38.jpg'::text, 'https://www.netflix.com/es/title/80191049'::text, 'Robert Johnson'::text, 'Mix'::text, 'netflix'::text, null::text),
  (58, '39.jpg'::text, 'https://www.netflix.com/es/title/81321471'::text, 'David Byrne'::text, 'Mix'::text, 'netflix'::text, null::text),
  (59, '40.jpg'::text, 'https://www.netflix.com/es/title/81466945'::text, 'Welcome to the Machine'::text, 'Mix'::text, 'netflix'::text, null::text),
  (60, '42.jpg'::text, 'https://www.youtube.com/watch?v=C3_g5nEDmVo'::text, 'El año que cambió el jazz'::text, 'Mix'::text, 'youtube'::text, null::text),
  (61, '43.jpg'::text, 'https://tv.apple.com/us/show/foo-fighters-sonic-highways/umc.cmc.40owu0t9i3pgms5pquaz9edvb?l=es'::text, 'Foo Fighters: Sonic Highways'::text, 'Mix'::text, 'Apple TV'::text, null::text),
  (62, '44.jpg'::text, 'https://Filmin.es/pelicula/unfinished-plan-el-camino-de-alain-johannes'::text, 'Unfinished plan: El camino de Alain Johannes'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (63, '45.jpg'::text, 'https://www.documaniatv.com/historia/sound-city-video_9324b3a17.html'::text, 'Sound City'::text, 'Mix'::text, 'Documania TV'::text, null::text),
  (64, '48.jpg'::text, 'https://www.documaniatv.com/biografias/20000-dias-en-la-tierra-nick-cave-video_91587dc67.html'::text, '20000 dias en la tierra (Nick Cave)'::text, 'Mix'::text, 'Documania TV'::text, null::text),
  (65, '50.jpg'::text, 'https://www.rtve.es/play/videos/imprescindibles/coque-malla/16145208/'::text, 'Jorge, una travesía de Coque Malla'::text, 'Mix'::text, 'rtve_play'::text, null::text),
  (66, '53.jpeg'::text, 'https://www.disneyplus.com/es-es/movies/abbey-road-if-these-walls-could-sing/6qV9r0UnbXdm'::text, 'Abbey Road si las paredes cantasen'::text, 'Mix'::text, 'disney+'::text, null::text),
  (67, '55.jpeg'::text, 'https://www.disneyplus.com/es-es/movies/bono-and-the-edge-a-sort-of-homecoming-with-dave-letterman/5slJjC2bpE0g'::text, 'Bono & The Edge a sort of homecoming with Dave Letterman'::text, 'Mix'::text, 'disney+'::text, null::text),
  (68, '56.jpeg'::text, 'https://www.filmin.es/pelicula/victor-manuel-el-abuelo-victor'::text, 'Victor Manuel. El abuelo Victor'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (69, '58.jpeg'::text, 'https://www.disneyplus.com/es-es/series/thank-you-goodnight-la-historia-de-bon-jovi/323NHrM5rTrj'::text, 'Thank you, good night. The Bon Jovi Story'::text, 'Mix'::text, 'disney+'::text, null::text),
  (70, '59.jpeg'::text, 'https://www.primevideo.com/-/es/detail/Rory-Gallagher---Ghost-Blues-The-Story-Of-Rory-Gallagher/0RIFW3DIDU4V1U8XQC0WGYQ4K8'::text, 'Ghost Blues. The Story of Rory Gallagher'::text, 'Mix'::text, 'primevideo'::text, null::text),
  (71, '60.jpeg'::text, 'https://www.atresplayer.com/lasexta/programas/salvados/temporada-21/supersubmarina-cien-maneras-de-volver-parte-1_6717ff594911b0e4b3bb8b87/'::text, 'Supersubmarina'::text, 'Mix'::text, 'atresplayer'::text, null::text),
  (72, '61.jpeg'::text, 'https://www.filmin.es/pelicula/la-estrella-azul'::text, 'La estrella azul'::text, 'Mix'::text, 'Filmin'::text, null::text),
  (73, '62.jpg'::text, 'https://www.rtve.es/play/videos/documaster/documaster-manera/16599731/'::text, 'a mi manera-My Way'::text, 'Mix'::text, 'RTVE Play'::text, null::text),
  (74, '63.jpg'::text, 'https://www.netflix.com/es/title/80102952'::text, 'Quincy'::text, 'Mix'::text, 'Netflix'::text, null::text),
  (75, '64.jpg'::text, 'https://www.netflix.com/es/title/81462290'::text, 'Elvis: El Regreso del rey'::text, 'Mix'::text, 'Netflix'::text, null::text),
  (76, '57.jpeg'::text, 'https://www.disneyplus.com/es-es/movies/bruce-springsteen-and-the-e-street-band-diarios-de-carretera/2pygKsgu73mm'::text, 'Bruce Springsteen & The E Street Band. Diarios de carretera'::text, 'Bruce Springsteen'::text, 'disney+'::text, null::text),
  (77, 'western_stars.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjW5azpy56CAxW0U6QEHVSyA0wQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fwestern-stars%2Fumc.cmc.4b56borzlb0le4hleommro07r&usg=AOvVaw1ErqeY0TKPMQyq_uO4Q9NP&opi=89978449'::text, 'Western Stars'::text, 'Bruce Springsteen'::text, 'Apple TV'::text, null::text),
  (78, 'springsteen.jpeg'::text, 'https://www.netflix.com/es/title/80232329?s=a&trkid=13747225&trg=more&vlang=es&clip=81008802'::text, 'Bruce Springsteen'::text, 'Bruce Springsteen'::text, 'netflix'::text, null::text),
  (79, 'rock_radikal_vasco.jpg'::text, 'https://www.youtube.com/watch?v=byd0judBk9c'::text, 'Rock Radikal Vasco II'::text, 'Rock Radikal Vasco'::text, 'youtube'::text, null::text),
  (80, 'rock_radikal_vasco.jpg'::text, 'https://www.youtube.com/watch?v=eqlsvtRzbG8'::text, 'Rock Radikal Vasco III'::text, 'Rock Radikal Vasco'::text, 'youtube'::text, null::text),
  (81, 'rock_radikal_vasco.jpg'::text, 'https://www.youtube.com/watch?v=Rw_4XgwKksU'::text, 'Rock Radikal Vasco IV'::text, 'Rock Radikal Vasco'::text, 'youtube'::text, null::text),
  (82, 'rock_radikal_vasco.jpg'::text, 'https://www.youtube.com/watch?v=8xyJ0xpVcz0'::text, 'Rock Radikal Vasco V'::text, 'Rock Radikal Vasco'::text, 'youtube'::text, null::text),
  (83, 'rock_radikal_vasco.jpg'::text, 'https://www.youtube.com/watch?v=GIODJAbAfVc'::text, 'Eskorbuto'::text, 'Rock Radikal Vasco'::text, 'youtube'::text, null::text),
  (84, '47.jpg'::text, 'https://www.arte.tv/es/videos/114775-000-A/heavy-metal-kingdom/'::text, 'Heavy Metal Kingdom'::text, 'Heavy Metal'::text, 'arte'::text, null::text),
  (85, '49.jpg'::text, 'https://www.arte.tv/es/videos/064208-001-A/el-barco-del-infierno-1-9/'::text, 'El barco del infierno (1/9)'::text, 'Heavy Metal'::text, 'arte'::text, null::text),
  (86, '46.jpg'::text, 'https://www.youtube.com/watch?v=NV8SGt2-xSs'::text, 'The Decline of Western Civilization Part II: The Metal Years'::text, 'Heavy Metal'::text, 'youtube'::text, null::text),
  (87, '18.jpeg'::text, 'https://www.youtube.com/watch?v=Hl9kELOgzAI'::text, 'Lemmy'::text, 'Heavy Metal'::text, 'youtube'::text, null::text),
  (88, 'metallica.jpeg'::text, 'https://www.netflix.com/es/title/80174429?s=a&trkid=13747225&trg=more&vlang=es&clip=81476513'::text, 'Metallica'::text, 'Heavy Metal'::text, 'netflix'::text, null::text),
  (89, 'mighty_good_the_beatles.jpg'::text, 'https://www.netflix.com/es/title/81471399?s=a&trkid=13747225&trg=more&vlang=es&clip='::text, 'Mighty Good'::text, 'the beatles'::text, 'netflix'::text, null::text),
  (90, 'how_the_beatles_changed_the_world.jpg'::text, 'https://www.netflix.com/es/title/80195654?s=a&trkid=13747225&trg=more&vlang=es&clip=81141331'::text, 'The Beatles'::text, 'the beatles'::text, 'netflix'::text, null::text),
  (91, 'john_lennon_love_is_all_you_need.jpg'::text, 'https://www.netflix.com/es/title/70233321?s=a&trkid=13747225&trg=more&vlang=es&clip=81494586'::text, 'John Lennon'::text, 'the beatles'::text, 'netflix'::text, null::text),
  (92, 'all_together_now.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi5zJfkxZ6CAxXWUqQEHazcDD0QFnoECA8QAQ&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fall-together-now%2Fumc.cmc.41me6g4yxgh94dpt2iu2v63iw&usg=AOvVaw3Flrq9hio8GXiJYCF-lduS&opi=89978449'::text, 'All Together now'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (93, 'concert_for_george.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiDxPWzzJ6CAxWZfKQEHZh0CU8QtwJ6BAgNEAI&url=https%3A%2F%2Ftv.apple.com%2Fes%2Fmovie%2Fconcert-for-george%2Fumc.cmc.5k3qb4dwsqc7nfmnlzy8bctq1&usg=AOvVaw1dqMAMKurf5CDEn_VOelmZ&opi=89978449'::text, 'Concert for George'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (94, 'the_beatles_help.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjA4MX_z56CAxWyUaQEHTP4BtgQtwJ6BAgQEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fhelp%2Fumc.cmc.3dix8n33y9glwds833f7imh2i%3Fl%3Des&usg=AOvVaw3mCZ2UTW4ZgjUTxzPJH6lO&opi=89978449'::text, 'Help!'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (95, 'the_beatles_eight_days.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiI2qnD0p6CAxUFV6QEHfATAU8QtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fthe-beatles-eight-days-a-week---the-touring-years%2Fumc.cmc.6sxri7yo7br98f4i9w2pc9hu5&usg=AOvVaw2gWdWlLWYYXGiVDp4Mo2x2&opi=89978449'::text, 'Eight days a week!'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (96, 'yesterday.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiLxojw056CAxXKVqQEHYqaA8wQtwJ6BAgPEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fyesterday%2Fumc.cmc.6e1v9fydp0lrsikw1jvcjcfbm&usg=AOvVaw1vChQ5Srb-3uQrB5US3Psl&opi=89978449'::text, 'Yesterday'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (97, '20.jpeg'::text, 'https://tv.apple.com/us/show/mccartney-321/umc.cmc.62zq0x2i794tnb4ybpfoolkrg?l=es'::text, 'Mc Cartney 3,2,1'::text, 'the beatles'::text, 'Apple TV'::text, null::text),
  (98, '21.jpeg'::text, 'https://www.disneyplus.com/es-es/series/the-beatles-get-back/7DcWEeWVqrkE'::text, 'Get Back'::text, 'the beatles'::text, 'disney+'::text, null::text),
  (99, '52.jpeg'::text, 'https://www.disneyplus.com/es-es/movies/the-beatles-let-it-be/71Oc25GCtPny'::text, 'Let it be'::text, 'the beatles'::text, 'disney+'::text, null::text),
  (100, '54.jpeg'::text, 'https://www.disneyplus.com/es-es/movies/beatles-64/mxZO6yBpYWOq'::text, 'Beatles 64'::text, 'the beatles'::text, 'disney+'::text, null::text),
  (101, 'rolling_stone_life_and_death_of_brian_jones.jpg'::text, 'https://www.netflix.com/es/title/81555057?s=a&trkid=13747225&trg=more&vlang=es&clip=81584958'::text, 'Brian Jones'::text, 'the rolling stones'::text, 'netflix'::text, null::text),
  (102, 'keith_richards_under_the_influence.jpg'::text, 'https://www.netflix.com/es/title/80066798?s=a&trkid=13747225&trg=more&vlang=es&clip=80078803'::text, 'Keith Richards'::text, 'the rolling stones'::text, 'netflix'::text, null::text),
  (103, 'stones_live.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiExcCB056CAxVfY6QEHVWbA1IQtwJ6BAgIEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fthe-rolling-stones-sweet-summer-sun-hyde-park-live%2Fumc.cmc.68qq01fj56unxsxviozpg2cja&usg=AOvVaw39PTNNDVfBr6NkChmGs0HZ&opi=89978449'::text, 'Live at Hyde Park'::text, 'the rolling stones'::text, 'Apple TV'::text, null::text),
  (104, 'stones_crossfire.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwiJlKm5056CAxXRUaQEHfNFAxwQtwJ6BAgNEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Fthe-rolling-stones-crossfire-hurricane%2Fumc.cmc.a0faxt7rf50xtbl7leebv0vl&usg=AOvVaw2S5E7cqMnVw8NvsKE4P1k1&opi=89978449'::text, 'Crossfire Hurricane'::text, 'the rolling stones'::text, 'Apple TV'::text, null::text),
  (105, 'mi_vida_como_un_stone.jpeg'::text, 'https://www.hbomax.com/es/es/series/urn:hbo:series:GYsxnnQs4y5HCEgEAAAAC'::text, 'The Rolling Stones'::text, 'the rolling stones'::text, 'hbo'::text, null::text),
  (106, '30.jpg'::text, 'https://vimeo.com/614942917'::text, 'The Rolling Stones R&R Circus'::text, 'the rolling stones'::text, 'vimeo'::text, null::text),
  (107, 'eric_clapton_the_1970s_review.jpg'::text, 'https://www.netflix.com/es/title/81506593?s=a&trkid=13747225&trg=more&vlang=es&clip=81583995'::text, 'The 1970s Review'::text, 'eric clapton'::text, 'netflix'::text, null::text),
  (108, 'eric_clapton_live_at_royal.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjZzd-fzZ6CAxW7SKQEHdq6DjIQtwJ6BAgMEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Feric-clapton---slowhand-at-70-live-at-the-royal-albert-hall%2Fumc.cmc.57x7tgjvpjeesswjdj7tcfz11&usg=AOvVaw18ID8G8nCF7lPVor627UpZ&opi=89978449'::text, 'Live at The Royal Albert Hall'::text, 'eric clapton'::text, 'Apple TV'::text, null::text),
  (109, 'eric_clapton_planes.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwi_qbCBzp6CAxVmVaQEHXGAC-QQtwJ6BAgOEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Feric-clapton-planes-trains-and-eric%2Fumc.cmc.1w7xc7qzk8qnkwxegc84obng3&usg=AOvVaw2uI7oF5hlS413p8caO3xll&opi=89978449'::text, 'Planes,Trains and Eric'::text, 'eric clapton'::text, 'Apple TV'::text, null::text),
  (110, 'eric_clapton_unplugged.jpeg'::text, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&ved=2ahUKEwjM4Le0zp6CAxXFUKQEHf-3CRoQtwJ6BAgMEAI&url=https%3A%2F%2Ftv.apple.com%2Fus%2Fmovie%2Feric-clapton-unplugged%2Fumc.cmc.1u9fzvr9nc5a18qndsigb6rd7%3Fl%3Des&usg=AOvVaw1sytk8pa4mIMl62Pv5rkmm&opi=89978449'::text, 'Unplugged'::text, 'eric clapton'::text, 'Apple TV'::text, null::text),
  (111, '51.jpg'::text, 'https://www.youtube.com/watch?v=TkO9xQKv8vs'::text, 'Clapton es Dios'::text, 'eric clapton'::text, 'youtube'::text, null::text),
  (112, 'monterey.jpg'::text, 'https://youtu.be/7MX2VEYpTfw?feature=shared'::text, 'Monterey 1967'::text, 'festivales'::text, 'youtube'::text, null::text),
  (113, 'woodstock.jpg'::text, 'https://youtu.be/1oNLLBXiZXw?feature=shared'::text, 'Woodstock 1969'::text, 'festivales'::text, 'youtube'::text, null::text),
  (114, 'farm_aid.jpg'::text, 'https://www.youtube.com/watch?v=f79fjaMOIiY'::text, 'Farm AID 1985'::text, 'festivales'::text, 'youtube'::text, null::text),
  (115, '32.jpg'::text, 'https://www.youtube.com/playlist?list=PLNYyB-jQI_J4wXjCc0t4FdIZZ-tl41vXz'::text, 'Live AID 1985'::text, 'festivales'::text, 'youtube'::text, null::text),
  (116, 'eskorbuto.jpg'::text, 'https://youtu.be/aUmY-8A3bZw?feature=shared'::text, 'Generación Anti Todo'::text, 'punk'::text, 'youtube'::text, null::text),
  (117, 'punk_in_london.jpeg'::text, 'https://www.netflix.com/es/title/70118168?s=a&trkid=13747225&trg=more&vlang=es&clip=81492312'::text, 'Punk in London'::text, 'punk'::text, 'netflix'::text, null::text),
  (118, 'rude_boy.jpeg'::text, 'https://www.netflix.com/es/title/81470754?s=a&trkid=13747225&trg=more&vlang=es&clip='::text, 'Rude Boy'::text, 'punk'::text, 'netflix'::text, null::text),
  (119, 'sex_pistols.jpeg'::text, 'https://youtu.be/ltz71Gt2PHg?feature=shared'::text, 'Sex Pistols'::text, 'punk'::text, 'youtube'::text, null::text),
  (120, 'lo_que_hicimos_fue_secreto.jpeg'::text, 'https://play.rtve.es/v/6809560'::text, 'Punk en Madrid'::text, 'punk'::text, 'rtve_play'::text, null::text),
  (121, 'gimme_danger.jpg'::text, 'https://www.Filmin.es/pelicula/gimme-danger'::text, 'The Stooges'::text, 'punk'::text, 'Filmin'::text, null::text),
  (122, '4.jpeg'::text, 'https://www.netflix.com/title/81555051'::text, 'Stiv no compromise no regrets'::text, 'punk'::text, 'netflix'::text, null::text),
  (123, '8.jpeg'::text, 'https://www.Filmin.es/pelicula/sid-y-nancy'::text, 'Sid y Nancy'::text, 'punk'::text, 'Filmin'::text, null::text),
  (124, '19.jpeg'::text, 'https://www.eitb.eus/es/nahieran/musica/no-somos-nada/5768/'::text, 'No somos nada'::text, 'punk'::text, 'eitb'::text, null::text),
  (125, '41.jpg'::text, 'https://drive.google.com/file/d/1ZL2can6GM1XM0lMogCmNH-S1AGBfy09E/view?fbclid=IwZXh0bgNhZW0CMTAAAR0RXL1GNgZzd6IvcPmsiuncSDB7Ren2YB9s_Qqy74M3LRRPyV-eyxFjGuw_aem_AYKrRRFeUZTg0zVwifx35QaYdGw06Ig59bGlsEMCKPZsJIZ1O8U8vxAn9gWp-lWvo2nlrOsFAb9tUhM8gubE12Uo'::text, 'A band called Death'::text, 'punk'::text, 'Google Drive'::text, null::text),
  (126, '9.jpeg'::text, 'https://www.netflix.com/title/81006953'::text, 'Rompan Todo'::text, 'latinoamerica'::text, 'netflix'::text, null::text),
  (127, '10.jpeg'::text, 'https://www.netflix.com/title/81219817'::text, 'Fito Paez'::text, 'latinoamerica'::text, 'netflix'::text, null::text),
  (128, '14.jpeg'::text, 'https://www.youtube.com/watch?v=jsBfg0OAjGM'::text, 'Charly Garcia-Piano Bar Sessions'::text, 'latinoamerica'::text, 'youtube'::text, null::text),
  (129, '15.jpeg'::text, 'https://www.youtube.com/watch?v=xX06uBssVCY'::text, 'Charly Garcia-Luna Park'::text, 'latinoamerica'::text, 'youtube'::text, null::text),
  (130, '22.jpeg'::text, 'https://www.youtube.com/watch?v=ssfD-Jhj7xo'::text, 'Sui Generis-Despedida'::text, 'latinoamerica'::text, 'youtube'::text, 'https://www.infobae.com/teleshow/infoshow/2020/09/05/a-45-anos-de-adios-sui-generis-2-recitales-los-27-porros-de-charly-la-pizza-de-nito-y-el-miedo-a-terminar-presos/'::text),
  (131, 'maquis.jpg'::text, 'https://www.atresplayer.com/lasexta/programas/lasexta-columna/temporada-13/columnas-de-la-historia-guerrilleros-de-ciudad-el-ejercito-fantasma-contra-franco-parte-i_6537877a7ea0b0e4ff304299/'::text, 'Maquis'::text, 'guerra_civil'::text, 'atresplayer'::text, null::text),
  (132, 'urraca.jpeg'::text, 'https://play.rtve.es/v/6988014'::text, 'Urraca'::text, 'guerra_civil'::text, 'rtve_play'::text, null::text),
  (133, 'heroinas.jpeg'::text, 'https://play.rtve.es/v/6834608'::text, 'Heroinas'::text, 'ii_guerra_mundial'::text, 'rtve_play'::text, null::text),
  (134, 'juego_de_espias.jpeg'::text, 'https://play.rtve.es/v/5779359'::text, 'Juego de espias'::text, 'ii_guerra_mundial'::text, 'rtve_play'::text, null::text),
  (135, 'pearl_harbor.jpeg'::text, 'https://play.rtve.es/v/6230470'::text, 'Pearl harbor'::text, 'ii_guerra_mundial'::text, 'rtve_play'::text, null::text),
  (136, 'el_pacifico.jpeg'::text, 'https://play.rtve.es/v/5976669'::text, 'El Pacífico'::text, 'ii_guerra_mundial'::text, 'rtve_play'::text, null::text),
  (137, 'carrera_a_la_victoria.jpeg'::text, 'https://play.rtve.es/v/5976668'::text, 'Carrera a la victoria'::text, 'ii_guerra_mundial'::text, 'rtve_play'::text, null::text)
)
insert into public.videos (
  imagen,
  enlace,
  texto,
  categoria,
  plataforma,
  info
)
select
  imagen,
  enlace,
  texto,
  categoria,
  plataforma,
  info
from source
order by ord;

commit;
