begin;

insert into public.grupos (nombre)
values
  ('Angel Stanich'),
  ('Aurora & The Betrayers'),
  ('BBK Live'),
  ('beck'),
  ('Bette Smith'),
  ('Big a Sherrod'),
  ('Black Sabbath'),
  ('Blind Faith'),
  ('Chicago All Stars'),
  ('Chris Cornell'),
  ('Chris Robinson Brotherhood'),
  ('Chuck Berry'),
  ('Chuck Prophet'),
  ('Clutch'),
  ('Corizonas'),
  ('Cracker'),
  ('Curtis Harding'),
  ('Danko Jones'),
  ('Def con dos'),
  ('Derby Motoreta''s Burrito Kachimba'),
  ('Diavlo'),
  ('Eels'),
  ('Eskorbuto'),
  ('Fantastic Negrito'),
  ('Fito'),
  ('Foo Fighters'),
  ('Freddie Mercury'),
  ('Fuel Fandango'),
  ('Fun Lovin Criminals'),
  ('G3'),
  ('Ghalia Volt'),
  ('Gin Lady'),
  ('Iggy Pop'),
  ('Incubus'),
  ('Iron Maiden'),
  ('Jace Everett'),
  ('Jamiroquai'),
  ('Janes Addiction'),
  ('Jeff Beck'),
  ('Jo Goes Hunting'),
  ('Joe Bonamassa'),
  ('Judas Priest'),
  ('Julian Lage Trio'),
  ('Julian Maeso'),
  ('Leon Benavente'),
  ('Lisa and the Lips'),
  ('Little Steven'),
  ('Living Colour'),
  ('Loquillo'),
  ('Los Chikos del maíz'),
  ('Los chikos del maíz'),
  ('Los DelTonos'),
  ('Los Enemigos'),
  ('Luis Aguile'),
  ('Luis Brea'),
  ('M Clan'),
  ('Maika Makovski'),
  ('Marilyn Manson'),
  ('Mark Knopfler'),
  ('Mark Lanegan'),
  ('Matthew Sweet'),
  ('Mi Capitan'),
  ('Miguel Rios'),
  ('Mike Farris'),
  ('Morgan'),
  ('Motley Crue'),
  ('Motorhead'),
  ('Neuman'),
  ('Niña Coyote eta Chico Tornado'),
  ('Nirvana'),
  ('Norah Jones'),
  ('Paul Weller'),
  ('Placebo'),
  ('Queen'),
  ('R.E.M.'),
  ('Ringo Starr'),
  ('Robe Iniesta'),
  ('Royal Blood'),
  ('Rufus T. Firefly'),
  ('Ruper Ordorika'),
  ('Russian Red'),
  ('Santiago Auserón'),
  ('Shemekia Copeland'),
  ('Sidonie'),
  ('Sotomonte'),
  ('Stanley Jordan'),
  ('StarCrawler'),
  ('Steve Winwood'),
  ('Supersuckers'),
  ('Sven Hammond'),
  ('The Faces'),
  ('The Magpie Salute'),
  ('The Pogues'),
  ('The Ramones'),
  ('The Sisters of Mercy'),
  ('The Soul Jacket'),
  ('The Wings'),
  ('Thin Lizzy'),
  ('Thomas Azier'),
  ('Tool'),
  ('Toto'),
  ('Triana'),
  ('Turbo Negro'),
  ('White Lies'),
  ('Xoel López')
on conflict (nombre) do nothing;

commit;
