begin;

with source (
  ord,
  titulo,
  categoria,
  autor,
  isbn,
  caratula,
  enlace,
  deposito_legal,
  editorial,
  protagonista,
  sinopsis
) as (
  values
  (1, $seed$La mejor banda del mundo$seed$::text, $seed$Biografía$seed$::text, $seed$Juan Crisóstomo Amezaga, Angel Landa$seed$::text, $seed$978-84-09-02526-8$seed$::text, $seed$la_mejor_banda_del_mundo.jpeg$seed$::text, $seed$https://www.amedisk.com/producto/la-mejor-banda-del-mundo-eskorbuto-libro/$seed$::text, $seed$BI-1807-2017$seed$::text, $seed$Hilargi Ediciones Musicales$seed$::text, $seed$Eskorbuto$seed$::text, $seed$Los autores cuentan, a través de dos realidades paralelas, la verdadera historia. Una de ellas escrita en primera persona, es la voz de un narrador que solo conoce a Eskorbuto por las referencias que llegaron a su pais, México, y que ahora, viajando por tierras de Bizkaia, contrapone a la sociedad de los años ochenta que vivio el surgimiento del grupo. Y la otra, en la interpretación de unos sueños imposibles, recrea por medio de algunos escritos de Iosu su actitud contestataria y quiere dejar claro cómo cambiar lo establecido. Todo gira al rededor de las geniales letras de Iosu: relatos de una mente sin igual que gritan con un gran sentido crítico y que el tiempo ha otorgado la verdadera dimension a sus temores. 

Con la muerte física de Iosu y Jualma en 1992 murió el espíritu de ESKORBUTO, pero continua vivienco entre nosotros la energía de su principal paladin, iosu Expósito, que sigue siendo un referente para las nuevas generaciones.$seed$::text),
  (2, $seed$Cantar hacia atrás y llorar$seed$::text, $seed$Biografía$seed$::text, $seed$Elvira Asensi$seed$::text, $seed$978-84-18282-84-3$seed$::text, $seed$mark_lanegan.jpeg$seed$::text, $seed$https://editorialcontra.com/producto/sing-backwards-and-weep/$seed$::text, $seed$B-19146-2022$seed$::text, $seed$www.editorialcontra.com$seed$::text, $seed$Mark Lanegan$seed$::text, $seed$El enorme legado de MARK LANEGAN, de una intensidad brutal, y su voz cruda y cavernosa son ya parte de la historia de la música popular. Poco antes de morir, Lanegan dejó escritas sus memorias: un documento desgarrador y honesto como pocos de una vida dura que, a pesar de llevarlo a las puertas de la muerte en diversas ocasiones, vivió con una pasión incombustible. 

Además de su singladura musical y de su formación como cantante con una de las voces de barítono más personales del rock, Lanegan relata sin ambages su condición de politoxicómano, alcohólico y adicto al sexo, y el sufrimiento personal que padeció y el que infligió a los que le rodeaban.

Plagado de anécdotas inolvidables, Sing Backwards and Weep es sin duda uno de los testimonios más sobrecogedores e inolvidables de la literatura del rock.$seed$::text),
  (3, $seed$Les Beatles 1956-1975$seed$::text, $seed$Biografía$seed$::text, $seed$Ernesto Assante$seed$::text, $seed$0-634-02229-6$seed$::text, $seed$les_beatles.jpeg$seed$::text, $seed$https://www.halleonard.com/product/306349/the-beatles-complete-chord-songbook$seed$::text, null::text, $seed$L'imprévu$seed$::text, $seed$The Beatles$seed$::text, $seed$¿Quién sabe cómo habría sido el mundo sin los Beatles? ¿Serían nuestras vidas las mismas hoy en día? ¿Habrían sido posibles las revoluciones culturales y sociales de los años 60 y 70 sin los "Fab Four"? Probablemente no. Lo que es seguro es que el mundo habría sido más triste y menos colorido, y cargado de mucho menos esperanza y alegría - dos elementos fundamentales de la filosofía de los Beatles. ¿Se puede imaginar la historia del siglo XX sin los Beatles? Imposible, incluso si se debe decir que los libros de historia generalmente no toman en cuenta la influencia que los "Cuatro chicos en el viento" podrían haber tenido en la sociedad occidental a partir de los años 60. Esta obra intenta dar una visión general. Algunos de estos eventos pueden parecer menores en la historia con H mayúscula, pero el impacto del grupo en los comportamientos, estilos de vida y formas de expresión artística desde los años 60 hasta nuestros días ha sido en realidad profundo y espectacular.$seed$::text),
  (4, $seed$Chord Songbook$seed$::text, $seed$Partituras$seed$::text, null::text, $seed$979-10-295-0863-9$seed$::text, $seed$chord_songbook.jpeg$seed$::text, $seed$https://www.cultura.com/p-les-beatles-1956-1975-les-annees-qui-ont-change-le-monde-9791029508639.html$seed$::text, null::text, $seed$http://www.halleonard.com$seed$::text, $seed$The Beatles$seed$::text, $seed$Esta gran colección presenta las 194 canciones escritas e interpretadas por The Beatles, transcritas especialmente aquí para guitarristas que tocan rasgueando, a partir de las grabaciones originales, en las tonalidades originales. Cada canción incluye símbolos de acordes, diagramas de acordes para guitarra y letras completas. También incluye una guía de interpretación útil y una discografía completa.$seed$::text),
  (5, $seed$White Album$seed$::text, $seed$analisis$seed$::text, $seed$Tomás Crespo$seed$::text, $seed$978-84-947493-5-3$seed$::text, $seed$white_album.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/the-beatles-white-album-cancion-a-cancion/978-84-947493-5-3$seed$::text, $seed$B-24126-2018$seed$::text, $seed$editorial california$seed$::text, $seed$The Beatles$seed$::text, $seed$Tras lanzar a lo largo de 1967 dos discos psicodélicos, ?Sgt.PepperŽs Lonely Hearts Club Band? y ?Magical Mistery Tour?, los Beatles emprendieron a principios del año siguiente un viaje que les llevó hasta la localidad india de Rishikesh. Aunque regresaron a Londres malhumorados y por separado, en la India habían vivido muchas experiencias de las cuales nacieron numerosas canciones. El grupo atravesaba entonces un periodo de cambios: acababan de crear una nueva empresa, Apple Corps, con la que querían tanto ser sus propios jefes como ayudar a otros artistas; y por si fuera poco, Lennon y McCartney se encontraban en un delicado momento personal, en plena transición de pareja sentimental. A pesar de ello, en este ambiente enrarecido, los Beatles grabaron entre los meses de mayo y octubre, una cantidad prodigiosa de canciones, buena parte de las cuales vio la luz el 22 de noviembre de 1968, hace ahora 50 años, en el disco doble ?The Beatles?, naturalmente más conocido como el ?White Album?. Sepamos algo más de ellas, una a una, canción a canción$seed$::text),
  (6, $seed$¿A la vista!$seed$::text, $seed$analisis$seed$::text, $seed$John Pring y Rob Thomas$seed$::text, $seed$978-84-666-6331-1$seed$::text, $seed$a_la_vista.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/beatles-a-la-vista/978-84-666-6331-1$seed$::text, $seed$B-16.717-2018$seed$::text, $seed$Orphans Publishing$seed$::text, $seed$The Beatles$seed$::text, $seed$Tras lanzar a lo largo de 1967 dos discos psicodélicos, ?Sgt.PepperŽs Lonely Hearts Club Band? y ?Magical Mistery Tour?, los Beatles emprendieron a principios del año siguiente un viaje que les llevó hasta la localidad india de Rishikesh. Aunque regresaron a Londres malhumorados y por separado, en la India habían vivido muchas experiencias de las cuales nacieron numerosas canciones. El grupo atravesaba entonces un periodo de cambios: acababan de crear una nueva empresa, Apple Corps, con la que querían tanto ser sus propios jefes como ayudar a otros artistas; y por si fuera poco, Lennon y McCartney se encontraban en un delicado momento personal, en plena transición de pareja sentimental. A pesar de ello, en este ambiente enrarecido, los Beatles grabaron entre los meses de mayo y octubre, una cantidad prodigiosa de canciones, buena parte de las cuales vio la luz el 22 de noviembre de 1968, hace ahora 50 años, en el disco doble ?The Beatles?, naturalmente más conocido como el ?White Album?. Sepamos algo más de ellas, una a una, canción a canción$seed$::text),
  (7, $seed$Los Young$seed$::text, $seed$Biografía$seed$::text, $seed$Jesse Fink$seed$::text, $seed$978-84-480-2673-8$seed$::text, $seed$los_young.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/los-young-los-hermanos-que-crearon-acdc/978-84-480-2673-8$seed$::text, $seed$B.24.413-2019$seed$::text, $seed$Planeta$seed$::text, $seed$AC/DC$seed$::text, $seed$AC/DC no hace rock and roll. Ellos son el rock and roll.

Este no es como ningún otro libro de música que hayas leído antes. Con más valoración crítica que pura biografía, cuenta la historia del mítico trío a través de once temas clásicos de la banda y revela algunos de los secretos personales y creativos que intervinieron en su nacimiento y desarrollo. Figuras importantes del largo camino de AC/DC hacia el estrellato se sinceran por primera vez, y los héroes olvidados que están tras el éxito de la banda reciben por fin el crédito y el reconocimiento que merecen. Se desafía el relato aceptado de los acontecimientos y emergen nuevos y sensacionales detalles que arrojan una luz distinta a la historia de la banda, especialmente sobre sus primeros años con Atlantic Records en Estados Unidos. Antiguos miembros de AC/DC y músicos de grupos como Guns N' Roses, Dropkick Murphys, Airbourne y Rose Tattoo aportan también su opinión sobre la magia de los Young. Su música nunca se ha andado con chiquitas. Tampoco lo hace este libro. Después de cuarenta años, puede que AC/DC tengan por fin el libro que merecen.$seed$::text),
  (8, $seed$Maneras de vivir$seed$::text, $seed$historias de Madrid$seed$::text, $seed$Fernando Navarro$seed$::text, $seed$978-84-122720-5-5$seed$::text, $seed$maneras_de_vivir.jpeg$seed$::text, $seed$https://www.casadellibro.com/libro-maneras-de-vivir/9788412272055/12512273$seed$::text, $seed$M-22870-2021$seed$::text, $seed$https://muddywatersbooks.es$seed$::text, $seed$Rosendo, Josele Santiago y Elvira Lindo$seed$::text, $seed$A lo largo de 2020 y 2021, a medida que el mundo cambiaba y se adaptaba a circunstancias extraordinarias, en Madrid, además, se asistía a la aparición de un mezquino nacionalismo —impulsado por intereses políticos— como supuesta defensa ante la ‘madrileñofobia’ que parecía extenderse por el resto del país. En ese proceso se acabó corrompiendo la palabra ‘libertad’ y Madrid, la ciudad abierta, también pretendía ser viciada y convertida en justo lo contrario de lo que siempre ha sido. El periodista y escritor Fernando Navarro reaccionó ante esa situación saliendo a las calles de su ciudad para conocer las historias que de verdad importaban, las de las personas anónimas que estaban luchando y resistiendo para preservar un estilo y una forma de entender la vida en los que la cultura era la llamada de todas las inquietudes.

Este libro reúne cuarenta de esas historias, protagonizadas por salas como El Sol, Libertad 8, Galileo o Clamores; la Cuesta de Moyano, el Museo del Prado, los cines de barrio y el Doré; el teatro Pavón y los alternativos de Arganzuela, bares como La Vía Láctea o el Palermo, librerías familiares, tiendas de vinilos, asociaciones vecinales, músicos callejeros, Los Enemigos, Johnny Burning...

Rosendo, Josele Santiago y Elvira Lindo fueron testigos directos y decidieron sumarse a la causa.$seed$::text),
  (9, $seed$Rockvolución empresarial$seed$::text, $seed$Gestión del conocimiento$seed$::text, $seed$Salva López$seed$::text, $seed$978-84-92452-80-4$seed$::text, $seed$rockvolucion.jpeg$seed$::text, $seed$https://www.empresaactiva.com/rock-volucion-empresarial_1$seed$::text, $seed$B-28.225-2011$seed$::text, $seed$https://www.empresaactiva.com$seed$::text, null::text, $seed$INNOVACIÓN, LIDERAZGO Y ROCK & ROLL!

¿Hubiera usted imaginado que alguien como Bruce Dickinson, el cantante de Iron Maiden, sería nombrado director de marketing de una compañía aérea? ¿O que alguien como Jon Bon Jovi sería designado asesor del presidente de los Estados Unidos? ¿O que una diva del pop como Lady Gaga sería nombrada directora creativa de una compañía como Polaroid? ¿O que Will.i.am, el cantante de Black Eyed Peas, sería investido director de innovación creativa de una multinacional tecnológica como Intel?

Todo esto ha sucedido ya, es una realidad aunque le cueste creer. El mundo de la empresa tiene mucho que aprender de los músicos, y este libro trata de explicar muchas de las lecciones que podemos aprender de ellos. Le sorprenderá la cantidad de buenas ideas de sus héroes que le habían pasado desapercibidas y que pueden ser la clave de una reinvención que el mundo necesita de un modo apremiante.

La música es mucho más de lo que parece ser.$seed$::text),
  (10, $seed$Eramos unos niños$seed$::text, $seed$Biografía$seed$::text, $seed$Rosa Pérez$seed$::text, $seed$978-84-9989-445-4$seed$::text, $seed$patti_smith.jpeg$seed$::text, $seed$https://www.casadellibro.com/libro-eramos-unos-ninos/9788426414052/1695339$seed$::text, $seed$B-26205-2012$seed$::text, $seed$Debolsillo$seed$::text, $seed$Patti Smith y Robert Mapplethorpe$seed$::text, $seed$Corría el mes de julio de 1967 y eran unos niños, pero a partir de entonces Patti Smith y Robert Mapplethorpe sellaron una amistad que solo acabaría con la muerte del gran fotógrafo, en 1989. De eso habla este espléndido libro de memorias, de la vida en común de estos artistas, los dos entusiastas y apasionados, que cruzaron a grandes pasos la periferia de Nueva York para llegar al centro neurálgico del nuevo arte. Fue así que acabaron instalándose en el hotel Chelsea y se convirtieron en los protagonistas de un mundo hoy ya perdido donde reinaban Allen Ginsberg, Andy Warhol y sus chicos, y se creaban las grandes bandas de música que marcaron los años finales del siglo XX, mientras el sida hacía estragos. Lejos de ser un libro triste y nostálgico, Éramos unos niños es un homenaje a la amistad sin trabas, y sus páginas cargadas de vitalidad y humor nos devuelven el sabor de esa gran ciudad donde hubo un tiempo en que casi todo era posible.$seed$::text),
  (11, $seed$El fin de semana perdido$seed$::text, $seed$Biografía$seed$::text, $seed$Iván Moldes$seed$::text, $seed$978-84-945652-3-6$seed$::text, $seed$john_lennon.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/john-lennon-el-fin-de-semana-perdido/978-84-945652-3-6$seed$::text, $seed$M-36054-2016$seed$::text, $seed$T&B Editores$seed$::text, $seed$John Lennon$seed$::text, $seed$John Lennon. El fin de semana perdido es el relato definitivo de uno de los capítulos más fascinantes y desconocidos en la biografía del músico.

La separación de John y Yoko, en septiembre de 1973, dio inicio a la etapa más creativa de Lennon al margen de The Beatles. Durante los dieciocho meses que estuvieron separados, registró álbumes producidos por Phil Spector, Harry Nilsson o Mick Jagger, y sus colaboraciones con Elton John o David Bowie llegaron al número uno de las listas.

Aquellos meses, bautizados por el propio Lennon como “El fin de semana perdido” en alusión a la película de Billy Wilder, no solo fueron los más productivos y exitosos de su carrera en solitario, sino que en el plano personal, recuperó la relación con su hijo Julian o su viejo amigo Paul McCartney. Tanto es así, que llegaron a realizar una jam session juntos y durante sus encuentros proyectaron el regreso de su antigua banda.

Una narración absorbente por la que desfilan los personajes que definen la época más salvaje del rock, con el telón de fondo de los abusos cometidos por la administración de Richard Nixon y el escándalo Watergate, que provocó la única dimisión en la historia de un presidente de Estados Unidos.$seed$::text),
  (12, $seed$Blues$seed$::text, $seed$Blues$seed$::text, $seed$Ted Gioia$seed$::text, $seed$978-84-17141-56-1$seed$::text, $seed$blues.jpeg$seed$::text, $seed$https://www.turnerlibros.com/libro/blues$seed$::text, $seed$M-11365-2018$seed$::text, $seed$https://www.turnerlibros.com$seed$::text, $seed$blues$seed$::text, $seed$Si alguien puede hablar de música con la documentación de un investigador, la pasión de un novelista y el amor por la anécdota de un fan, ese es Ted Gioia.

Tras su monumental Historia del Jazz, ahora invita al lector a un viaje desde las plantaciones del Mississippi, donde nació el blues, para irse “a husmear un tiempo por Memphis y establecerse al fin en Chicago” (Peter Guralnick). Veremos cómo el blues “tuvo un hijo al que le llamaron rock and roll” (Muddy Waters), y cómo dejó sentir su influencia sobre varias generaciones de músicos, empezando por Elvis Presley.

El meticuloso trabajo de campo del autor (“para entender no sólo a los músicos, sino a su música”, Boston Globe) le permite además trazar con pulso firme el entorno económico, social y racial de unos músicos que conquistaron el mundo desde el peldaño más bajo.$seed$::text),
  (13, $seed$Mi Historia$seed$::text, $seed$Biografía$seed$::text, $seed$Manuel de la Fuente$seed$::text, $seed$978-84-17141-56-1$seed$::text, $seed$the_who.jpeg$seed$::text, $seed$https://www.librosdelkultrum.com/product/mi-historia-memorias-del-fundador-de-the-who/$seed$::text, $seed$M-11365-2018$seed$::text, $seed$https://www.librosdelkultrum.com$seed$::text, $seed$The Who, Roger Daltrey$seed$::text, $seed$Roger Daltrey —cantante, tunante y fundador del cuarteto The Who— es la voz de una generación, la primera en rebelarse contra las sombrías miserias y privaciones de la Segunda Guerra Mundial… para redefinir, en tan necesario empeño, la propia figura del artista adolescente. De su puño y letra, cúentase aquí la historia desde su nacimiento — en los peores días de los bombardeos que asolaron la capital londinense—, pasando por sus no menos tempestuosas andanzas escolares; colmadas, para mayor gloria, con su temprana expulsión, a los 15 años

Evocación de un trauma que tórnase en agradecimiento al autoritario e inmisericorde verdugo, Mr. Kibblewhite, temido director del centro; pues, como señala al poco del arranque, de no ser por tan providencial expulsión hubiera muy probablemente seguido la suerte que parecía aguardar a todos los de su condición.

Pero luego hízose el rock ‘n’ roll. Construiría con sus propias manos su primera guitarra valiéndose de los desechos del taller donde, además, procurábase el sustento. Formaría su primera banda. La banda se convertiría en The Who —Maximum R&B—y, por su inquebrantable determinación, Roger Daltrey se proclamaría líder de uno de los grupos de rock más grandes de la época. Esta es la historia de My Generation, Tommy y Quadrophenia, orquestada con agonizantes trinos de guitarras destrozadas, ecos de tambores pateados y proyectados hacia el respetable, peleas, arrestos, coches aparcados en piscinas, voladuras de inodoros… y otras instalaciones artísticas.Pero es también la historia de cómo la generación de la posguerra revolucionó los usos y costumbres de la juventud. Caldo de cultivo metamórfico del que brotaría la industria de la música moderna —y no fue parto fácil—. Dinero, drogas y unas gotas de exuberancia juvenil confluirían en una explosiva mezcla.

Tras cuatro años de maceración lenta, he aquí la intrahistoria del inefable cuarteto; la respuesta definitiva a la pregunta formulada en el propio nombre de la banda. Una crónica sincera y descarnada de más de medio siglo en la carretera. Así pues, con la indebida inmodestia, y sin más preámbulos, la historia definitiva de los Who; y de la revolución que sacudiría los aún endebles cimientos del rock ‘n’ roll británico.$seed$::text),
  (14, $seed$Starman$seed$::text, $seed$Biografía$seed$::text, $seed$Paul trynka$seed$::text, $seed$978-84-8428-667-7$seed$::text, $seed$bowie.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/david-bowie-starman-la-biografia-definitiva/978-84-8428-667-7$seed$::text, $seed$B-32.739-11$seed$::text, $seed$http://www.albaeditorial.es$seed$::text, $seed$David Bowie$seed$::text, $seed$Conocido como el "camaleón" de la música por su brillante creatividad y constante reinvención, David Bowie se ha convertido en un icono de nuestro tiempo. Sin embargo, a pesar de su gran popularidad, su vida y personalidad siguen siendo un enigma.

Con esta minuciosa biografía, Paul Trynka ha escrito su retrato definitivo: desde los años de infancia en el Brixton de la posguerra hasta el glamour decadente de Ziggy Stardust pasando por su controvertido periodo berlinés.

Basada en cientos de entrevistas a amigos y detractores, examantes y compañeros de profesión, "David Bowie: Starman" revela cómo el joven David Jones se transformó en David Bowie y cómo construyó su carrera artística y musical. Asimismo, recorre la vida de otros grandes artistas, como Lou Reed, Iggy Pop o Mick Jagger, que se cruzaron en la vida de Bowie y tuvieron una estrecha colaboración con él.$seed$::text),
  (15, $seed$Heavier than Heaven$seed$::text, $seed$Biografía$seed$::text, $seed$Charles R.Cross$seed$::text, $seed$978-84-16709-37-3$seed$::text, $seed$heavier_than_heaven.jpeg$seed$::text, $seed$https://www.penguinlibros.com/es/biografias/230198-libro-heavier-than-heaven-9788418052453?mot_tcid=bea9ccc1-dfe2-4f95-893e-536a3c875a97$seed$::text, $seed$B-22.660-2016$seed$::text, $seed$https://www.penguinlibros.com/es/11345-reservoir-books$seed$::text, $seed$Kurt Cobain$seed$::text, $seed$El suicidio fue el último acto que definió la personalidad de Kurt Cobain, tras una existencia repleta de rabia, dolor e inspiración. En esta biografía ya clásica, el periodista Charles R. Cross pone su extenso conocimiento de la escena de Seattle al servicio de la narración de una vida fascinante.

Tras más de cuatrocientas entrevistas y cuatro años de investigación, en los que tuvo acceso a todo tipo de documentos privados, el autor traza una panorámica del músico desde su adolescencia, cuando vivía en una caravana, hasta el momento en que alcanzó la fama y el fervor de toda una generación.

Charles R. Cross ha escrito un prefacio para esta nueva edición, donde da cuenta de los sucesos relacionados con Cobain y el propio libro durante las más de dos décadas transcurridas desde la muerte del artista.$seed$::text),
  (16, $seed$Memorias$seed$::text, $seed$Biografía$seed$::text, $seed$Helena Alvares de la Miyar$seed$::text, $seed$978-84-19942-080-6$seed$::text, $seed$vida.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/vida-memorias-de-keith-richards/978-84-480-2443-7$seed$::text, $seed$B-38983-LIII$seed$::text, $seed$Global Rythm Press$seed$::text, $seed$The Rolling Stones, Keith Richards$seed$::text, $seed$Keith Richards se ha dedicado a vivir una vida bajo sus propias normas. En esta célebre autobiografía Richards se sincera sobre su niñez, sobre cómo aprendió a tocar la guitarra y formó su banda junto a Jagger y Brian Jones, sobre los conciertos, las giras y los discos grabados, sobre su tensa relación con Jagger y sus romances, sobre su lucha contra la adicción a las drogas y sus consecuentes desencuentros con la ley en distintos países.$seed$::text),
  (17, $seed$Fui el camello$seed$::text, $seed$Biografía$seed$::text, $seed$Tony Sánchez$seed$::text, $seed$978-84-940938-2-1$seed$::text, $seed$yo_fui_el_camello.jpeg$seed$::text, $seed$https://editorialcontra.com/producto/yo-fui-el-camello-de-keith-richards$seed$::text, $seed$B.423-2013$seed$::text, $seed$https://editorialcontra.com$seed$::text, $seed$The Rolling Stones, Keith Richards$seed$::text, $seed$Tony Sánchez fue testigo del meteórico ascenso a la fama de los Rolling Stones. Formó parte del núcleo duro de la banda desde mediados de los años 60 y a lo largo de la década de los 70 y fue amigo personal de Mick Jagger, Keith Richards y del malogrado Brian Jones. Su privilegiada posición con respecto a la vida e intimidad de los Stones dio lugar a una de las biografías más originales, gamberras y trepidantes de la banda de rock más famosa del mundo.

«Spanish Tony», con sus buenos contactos en el lumpen londinense, se convirtió rápidamente en el camello de la banda y de sus aristocráticas amistades. A él recurrían cuando querían comprar drogas, lo que sucedía muy a menudo, sobre todo cuando el consumo se convirtió en adicción. Pero Sánchez fue mucho más que el dealer de la banda, ocupándose de toda una serie de tareas más o menos profesionales en calidad de «ayudante» de Keith Richards. Era el que lo sacaba de apuros cuando el coche del guitarrista acababa en siniestro total, o el que consolaba a las ilustres mujeres de los Stones, como Marianne Faithfull o Anita Pallenberg, cuando estos desaparecían o estaban ocupados alimentando otras pasiones.

Sánchez vivió de cerca algunos de los momentos álgidos de la carrera de la banda: sus conciertos más gloriosos, aunque también los más trágicos —su relato de la debacle de Altamont es prodigioso—; sus altercados con los tribunales y la persecución que padecieron por parte del «establishment» y sus resortes, las traiciones y rencillas que se produjeron en el seno de los Stones, las transfusiones de sangre en Suiza a las que se sometieron para eludir la justicia, los escarceos en el cine de Mick Jagger, la vida salvaje en Nellcôte durante la grabación de «Exile on Main St»…

«Yo fui el camello de Keith Richards» es un libro memorable, entre el culebrón desenfrenado y la crónica más vívida, plagado de anécdotas y momentos imborrables, quizá la biografía que rinde un más sincero homenaje a la célebre tríada del buen canalla: sexo, drogas y rock ‘n’ roll.$seed$::text),
  (18, $seed$The Rolling Stones$seed$::text, $seed$Biografía$seed$::text, null::text, $seed$84-08-04936-4$seed$::text, $seed$stones.jpeg$seed$::text, $seed$https://editorialcontra.com/producto/yo-fui-el-camello-de-keith-richards$seed$::text, $seed$B.423-2013$seed$::text, $seed$Planeta$seed$::text, $seed$The Rolling Stones$seed$::text, $seed$Aquí está la verdadera historia: la historia de los Rolling Stones, según los propios Rolling Stones. Mick Jagger, Keith Richards, Charlie Watts y Ronnie Wood se han reunido para hacer este increíble libro. Han abierto sus archivos personales y también los archivos del grupo para poder incluir muchas fotografías inéditas o íntimas que están entrelazadas con su gran historia de cuarenta años haciendo música juntos.

According to the Rolling Stones va directo a lo que hace latir el corazón de los Stones, como músicos, letristas, artistas y como amigos. Describen la evolución de su música y cómo ha afectado y cambiado sus vidas. También revelan, con una refrescante franqueza, la forma en que sus propias vidas han potenciado o perjudicado su labor como músicos.

Cada Stone nos ofrece su propio punto de vista sobre los sucesos e influencias de la banda, unas opiniones que son profundas, graciosas, conmovedoras, sorprendentes y, sobre todo, completamente auténticas. Comienzan hablando de sus raíces: sus raíces personales en el sur de Inglaterra y sus raíces musicales en el R&B que los unieron como grupo. Los acompañaremos desde sus primeras actuaciones en pequeños garitos donde Mick apenas tenía sitio para moverse hasta los grandes estadios con sus impresionantes escenarios, desde sus comienzos como banda que hacía versiones de canciones de otros hasta convertirse en la "banda de rockŽnŽroll más grande del mundo". Los Stones son un viaje que empezó con un éxito casi inmediato y con las consiguientes e inevitables presiones. También es un viaje cuyo trayecto sólo pueden contar de verdad los propios Stones.

According to the Rolling Stones está lleno de vívidos recuerdos tanto escritos como gráficos. Contiene cientos de fotografías, la mayoría de ellas inéditas. Se han seleccionado cuidadosamente las mejores imágenes de los archivos personales de los Stones, del archivo central del grupo y de los mejores fotógrafos, como David Baley, Gered Mankowitz, Terry OŽNeill, Mario Testino y Val Wilmer, que han seguido a la banda sobre el escenario, fuera de él y en el estudio durante cuatro décadas. Además, las guardas están decoradas con los cuadros que Ronnie ha hecho de sus compañeros de grupo.

Intercalados entre los recuerdos de los propios Stones hay unas breves reflexiones escritas por las personas que han sido claves en su historia. Gente tan cercana a ellos como el director de Atlantic Records, Ahmet Ertegun; su manager, Prince Rupert Loewenstein, y Sheryl Crow, que ha sido telonera en muchos de los conciertos de los Stones, ofrecen una perspectiva singular de la banda. Este imprescindible volumen se completa con un valioso quién es quién y una sección de consulta que incluye la discografía y la cronología completas de los Stones.$seed$::text),
  (19, $seed$Born to run$seed$::text, $seed$Biografía$seed$::text, $seed$Bruce Springsteen$seed$::text, $seed$978-84-940938-2-1$seed$::text, $seed$born_to_run.jpeg$seed$::text, $seed$https://www.penguinlibros.com/es/biografias/36958-libro-born-to-run-edicion-en-lengua-espanola-9788439731825?mot_tcid=9376f7b2-3667-4e46-9906-c7fa581e782b$seed$::text, $seed$B.423-2013$seed$::text, $seed$https://www.penguinlibros.com/es/11353-random-house$seed$::text, $seed$The Rolling Stones, Keith Richards$seed$::text, $seed$«Escribir sobre uno mismo es algo muy curioso. [...]. Pero en un proyecto como este el escritor hace una promesa: mostrarle su mente al lector. Y eso es lo que he intentado hacer en estas páginas.» Bruce Springsteen, extracto de Born to Run

En 2009, Bruce Springsteen y la E Street Band actuaron durante el intermedio de la Super Bowl. La experiencia fue tan maravillosa que Bruce se propuso escribir sobre ello. Así comenzó esta extraordinaria autobiografía.

Durante los últimos siete años, Bruce Springsteen se ha dedicado a escribir en privado la historia de su vida, dotando a estas páginas de la misma honestidad, humor y originalidad que encontramos en sus canciones.

Describe sus primeros años como chaval católico en Freehold, Nueva Jersey, en un ambiente donde la poesía, el peligro y la oscuridad alimentaban su imaginación, hasta que llega el momento que él denomina «el Big Bang»: cuando vio en televisión el debut de Elvis Presley en The Ed Sullivan Show. Nos cuenta vívidamente su incansable voluntad de convertirse en músico, sus primeros tiempos como rey de las bandas de bar en Asbury Park, y el ascenso de la E Street Band. Con un candor desarmante, cuenta también por vez primera las angustias personales que inspiraron sus mejores obras, y explica porqué la canción «Born to Run» revela mucho más de lo que pensábamos.

Born to Run será una revelación para cualquiera que en algún momento haya disfrutado de Bruce Springsteen, pero estas páginas son mucho más que las memorias de una legendaria estrella de rock. Es un libro para trabajadores y soñadores, padres e hijos, amantes y solitarios, artistas, friquis, o para cualquiera que alguna vez haya anhelado ser bautizado en el sagrado río del rock'n'roll.$seed$::text),
  (20, $seed$Lemmy$seed$::text, $seed$Biografía$seed$::text, $seed$Oscar Palmez Yáñez$seed$::text, $seed$978-84-940298-8-2$seed$::text, $seed$lemmy.jpeg$seed$::text, $seed$http://espop.es/catalogo/es-pop-ensayo/lemmy$seed$::text, $seed$M-36536-2014$seed$::text, $seed$http://espop.es$seed$::text, $seed$Motorhead, Lemmy$seed$::text, $seed$«Si piensas que eres demasiado viejo para el rock ‘n’ roll, es que lo eres». Así hablaba Ian «Lemmy» Kilmister, legendario líder de Motörhead y uno de los rockeros más incombustibles del planeta. Si hay que dar por buena la opinión de los médicos, Lemmy nunca debería haber sobrevivido a los años 80. Cinco décadas dedicadas en cuerpo y alma a la música, ganándose a pulso la fama de ser el tipo más bebedor, espídico y salidorro que haya pisado jamás un escenario, habían convertido su sangre en un mejunje capaz de matar a cualquier otro ser humano.

Su historia es la historia de la música rock desde sus inicios y hasta nuestros días. Lemmy abandonó su hogar en Gales para vivir en primera fila el estallido de la beatlemanía y tocar en conjuntos de merseybeat, soul y rhythm & blues, fue roadie de Jimi Hendrix y miembro de grupos tan singulares como The Rocking Vicars y Sam Gopal, antes de saltar a la fama como bajista de Hawkwind, el célebre conjunto de rock cósmico y espacial inspirado por Michael Moorcock, junto a los que interpretó himnos incontestables de la época como “Urban Guerrilla” y “Silver Machine”.

En 1975 fundó Motörhead, tan herederos de Chuck Berry como de MC5; decanos del heavy, primos bastardos del punk y precursores del speed metal. Las formaciones de Motörhead han sufrido numerosos cambios en sus más de treinta años de historia, pero Lemmy permaneció incombustible y en activo al frente de la banda hasta su fallecimiento en diciembre de 2015, recién cumplidos los 70 años. Lemmy: la autobiografía ofrece un viaje hilarante, desenfrenado y siempre sorprendente en compañía del líder de la «banda más ruidosa del mundo». Su historia y sus opiniones, narradas en primera persona, sin prejuicios y sin pelos en la lengua. El propio Lemmy lo advierte: «Si te ofendes con poca cosa, ¿qué haces leyendo este libro?».$seed$::text),
  (21, $seed$Teoría Musical y Armonía Moderna Vol. I$seed$::text, $seed$lenguaje musical$seed$::text, $seed$Enric Herrera$seed$::text, $seed$84-85855-31-0$seed$::text, $seed$enric_herrera_1.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/teoria-musical-y-armonia-moderna-1/978-84-85855-31-5$seed$::text, $seed$B-16.402-2001$seed$::text, $seed$Antoni Bosh$seed$::text, null::text, $seed$El músico y estudiante de música de nuestro país ha tenido que formarse, en cuanto a la música moderna y el jazz se refiere, a base de acumular experiencia tocando en grupos y orquestas, y sobre todo escuchando mucha música con el fin de aprender de una forma autodidacta lo que músicos de otros países han aprendido muchas veces al lado de grandes maestros o en Universidades o escuelas especializadas en esta enseñanza.

Este método puede ayudar a que estas personas clarifiquen las lagunas que la enseñanza autodidacta no puede resolver. Creo que puede ser de ayuda para los principiantes desde el inicio y también para aquellos que, dada su experiencia musical, ya poseen un buen nivel, al contribuir a la homogeneización de sus conocimientos."(E. Herrera)$seed$::text),
  (22, $seed$Teoría Musical y Armonía Moderna Vol. II$seed$::text, $seed$lenguaje musical$seed$::text, $seed$Enric Herrera$seed$::text, $seed$84-85855-45-0$seed$::text, $seed$enric_herrera_2.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/teoria-musical-y-armonia-moderna-2/978-84-85855-45-2/$seed$::text, $seed$B-37.602-1996$seed$::text, $seed$Antoni Bosh$seed$::text, null::text, $seed$El músico y estudiante de música de nuestro país ha tenido que formarse, en cuanto a la música moderna y el jazz se refiere, a base de acumular experiencia tocando en grupos y orquestas, y sobre todo escuchando mucha música con el fin de aprender de una forma autodidacta lo que músicos de otros países han aprendido muchas veces al lado de grandes maestros o en Universidades o escuelas especializadas en esta enseñanza.

Este método puede ayudar a que estas personas clarifiquen las lagunas que la enseñanza autodidacta no puede resolver. Creo que puede ser de ayuda para los principiantes desde el inicio y también para aquellos que, dada su experiencia musical, ya poseen un buen nivel, al contribuir a la homogeneización de sus conocimientos."(E. Herrera)$seed$::text),
  (23, $seed$Que rule el amor$seed$::text, $seed$Biografía$seed$::text, $seed$David Ritz$seed$::text, $seed$978-84-121842-3-5$seed$::text, $seed$lenny_kravitz.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/teoria-musical-y-armonia-moderna-2/978-84-85855-45-2/$seed$::text, $seed$B-19767-2020$seed$::text, $seed$https://www.librosdelkultrum.com$seed$::text, $seed$Lenny Kravitz$seed$::text, $seed$"Que rule el amor" es una ferviente y sentida invocación al principio activo que enhebra la vida y obra del roquero judeoantillano acaso más ecléctico que diera aquella quinta estadounidense, mas también un alto en el camino que anuncia tiempo de reflexión. De ese afán por echar la vista atrás y desgranar las esencias de una obra tildada de extemporánea en sus primeros compases, y encumbrada ahora a lo más alto del pedestal roquero, emerge este pausado alegato ?no exento de cierta candidez, inopinada psicogeografía, autoanálisis panteísta e inmisericorde humor?, narrado a capela, y escrito a cuatro manos, con la inestimable ayuda de David Ritz; escriba y confesor, entre otros, de Ray Charles, Aretha Franklin, Marvin Gaye, Etta James y B. B. King. No corrían buenos tiempos para el rock cuando, tras unos primeros tientos inciertos, Kravitz enfrentábase ?a contracorriente, para mayor gloria? a las modas del momento: en la cresta de la ola, rugía la incipiente insurgencia que, a hombros de sus conversos, hacía que el hip hop arrasara con los cimientos de la propia industria discográfica y, en el extremo más conservador, se resistía a fenecer la despampanante opulencia de las reliquias del rock más duro y grandilocuente que gastaban por aquel entonces sus más pálidos coetáneos. «Mi vida tiene que ver con los opuestos», subraya. «Blanco y negro. Judío y cristiano. Jackson Five y Led Zeppelin. Puro Géminis.» Es esta la historia de una vocación temprana que, pese a una muy lenta germinación ?rechazaría contratos con las más grandes discográficas hasta dar con su propia voz? tendría final feliz: Lenny, mientras se curtía tocando por doquier, y sobrevivía pinchando en fiestas, rebozando pescado y alquilando el asiento trasero de un auto como vivienda, encontraría la salvación en la música, en el Todopoderoso (Little Richard mediante) y en el amor incondicional de los suyos.$seed$::text),
  (24, $seed$Más extraño que la bondad$seed$::text, $seed$Biografía$seed$::text, $seed$Mariano Peyrou$seed$::text, $seed$978-84-118342-57-8$seed$::text, $seed$nick_cave.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/mas-extrano-que-la-bondad/978-84-18342-57-8$seed$::text, $seed$M-22811-2021$seed$::text, $seed$http://www.sextopiso.com$seed$::text, $seed$Nick Cave$seed$::text, $seed$Más extraño que la bondad nos ofrece una fascinante mirada íntima al universo creativo de uno de los artistas más relevantes del panorama musical contemporáneo, Nick Cave. A través de fotografías, libretas de apuntes, letras de canciones escritas a mano y una colección de objetos artísticos que moldearon su muy particular imaginario, este libro traza el origen y desarrollo de una imponente carrera musical, a la manera de un rompecabezas donde cada una de las piezas contribuye a formar una imagen cuyo rostro nos resulta sumamente familiar. Y es el propio Cave quien ofrece a los lectores una visita guiada por cada una de las paradas que lo condujeron al estrellato. 

Se trata de una suerte de diario íntimo visual y escrito en el que se registran los deseos, fantasías, temores y obsesiones de ese artista tan radicalmente único que es Nick Cave. Una celebración de los misterios del proceso creativo en tanto que lenguaje universal, que en el caso de Cave ha logrado conectar con millones de personas a lo largo del planeta. Un viaje en el que música, poesía, fotografía, pintura y devoción por el rock n’ roll convergen como testimonio de una de las expresiones musicales más estremecedoras de las últimas décadas.$seed$::text),
  (25, $seed$Autobiografía$seed$::text, $seed$Biografía$seed$::text, $seed$Puerto Barruetabeña Diez$seed$::text, $seed$978-84-15887-45-4$seed$::text, $seed$clapton.jpeg$seed$::text, $seed$https://www.alfaomega.es/libros/?texto=clapton&action=busqueda_rapida$seed$::text, $seed$M.13.745-2019$seed$::text, $seed$https://www.alfaomega.es$seed$::text, $seed$Eric Clapton$seed$::text, $seed$«ENCONTRÉ UN PATRÓN EN MI COMPORTAMIENTO QUE LLEVABA AÑOS  REPITIÉNDOSE, DÉCADAS INCLUSO. LAS MALAS ELECCIONES ERAN MI  ESPECIALIDAD, Y SI ME SURGÍA ALGO DECENTE Y SINCERO, LO RECHAZABA O SALÍA CORRIENDO».—ERIC CLAPTON$seed$::text),
  (26, $seed$I Will alway love you$seed$::text, $seed$Historia$seed$::text, $seed$Marisa Morea$seed$::text, $seed$978-84-16890-58-3$seed$::text, $seed$i_will_always.jpeg$seed$::text, $seed$https://www.planetadelibros.com/libro-i-will-always-love-you/262459$seed$::text, $seed$B-24435-2017$seed$::text, $seed$https://www.planetadelibros.com/editorial/lunwerg-editores/31$seed$::text, null::text, $seed$Te querré siempre es un recorrido por las mejores historias de amor de la música. Parejas unidas en lo personal y en lo profesional que nos hicieron creer que el amor podía ser eterno, pero que finalmente se separaron y solo nos dejaron un puñado de canciones. ¡Pero qué canciones! Este libro toma el título del celebérrimo tema I will Always Love You, interpretado por la angelical Whitney Houston, que cayó en los infiernos durante su matrimonio con Bobby Brown. Además de ellos, en este libro aparecerán: Mick Jagger y su primera musa, Marianne Faithfull; el Verano del Amor de Nico y Jim Morrison; Jane Birkin y Serge Gainsbourg, con su chic francés; los siempre complicados PJ Harvey y Nick Cave… ¡y muchas parejas (y canciones) más…!$seed$::text),
  (27, $seed$Stone Free$seed$::text, $seed$Biografía$seed$::text, $seed$jas Obrechet$seed$::text, $seed$978-84-480-2746-9$seed$::text, $seed$stone_free.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/stone-free-jimi-hendrix-de-londres-a-monterrey-los-nueve-meses-que-cambiaron-la-historia-del-rock/978-84-480-2746-9$seed$::text, $seed$B-5.894-2020$seed$::text, $seed$Planeta$seed$::text, $seed$Jimi Hendrix$seed$::text, $seed$Jas Obrecht captura el frenesí y la emoción del momento más extraordinario en la historia de la guitarra, cuando Jimi Hendrix reinventa la guitarra eléctrica, se convierte en una superestrella internacional." (Joe Satriani)

"Stone Free" es el cautivador retrato del guitarrista más grande del rock de todos los tiempos en el momento de su ascenso, el primer libro que se centra exclusivamente en el periodo más feliz y productivo en la vida de Jimi Hendrix, los nueve meses que pasó en Londres: era el héroe del "swinging London", un icono de la moda, creador de tendencias, el rockero más fascinante de Londres según Mick Jagger y convertido en la estrella más brillante que pisó el escenario del histórico Festival Internacional de Música Pop de Monterey.

Esta narración de la deslumbrante transformación del guitarrista proporciona nuevos detalles sobre la personalidad de Hendrix, sus relaciones, sus composiciones, las innovaciones que introdujo en la guitarra, las grabaciones en el estudio y el lanzamiento de sus discos. Bucea por los recuerdos de músicos, amigos, periodistas, representantes, técnicos de sonido, técnicos de gira y, por supuesto, a través de las palabras del propio Jimi Hendrix.$seed$::text),
  (28, $seed$La Biografía$seed$::text, $seed$Biografía$seed$::text, $seed$Charles R. Cross$seed$::text, $seed$978-84-96222-80-9$seed$::text, $seed$room_full_of_mirrors.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/room-full-of-mirrors-jimi-hendrix-la-biografia/978-84-96222-80-9$seed$::text, $seed$B-5.473-2007$seed$::text, $seed$Robinbook$seed$::text, $seed$Jimi Hendrix$seed$::text, $seed$«Room Full of Mirrors» es una de las canciones más conocidas de Jimi Hendrix, uno de los mejores guitarristas del siglo XX y, sin duda, emblema de todo cuanto supusieron los años sesenta.

Sin embargo, más allá de los meros tópicos sobre su virtuosismo y su estilo de vida desenfrenado, apenas se conoce nada sobre él. Su aureola mítica ha impedido que se comprenda en su justa medida la lucha que debió librar consigo mismo y contra un "stablishment" que tan sólo lo consideraba como un músico apto para el circuito reservado a la comunidad negra estadounidense.

A diferencia de otras biografías, ésta recorre toda la vida del genial guitarrista: su conflictiva infancia en Seattle, las primeras tentativas en el mundo musical, la temprana muerte de su madre, la lucha contra los prejuicios raciales y su rápido ascenso gracias a su irrupción en la escena londinense. En ella descubrimos uno de los mayores misterios de la historia del rock: la leyenda de alguien que se enfrentó a la miseria y el desprecio hasta convertirse en uno de los personajes más legendarios y perdurables de nuestra época.$seed$::text),
  (29, $seed$England's Dreaming$seed$::text, $seed$Análisis$seed$::text, $seed$Jon Savage$seed$::text, $seed$978-84-16709-65-6$seed$::text, $seed$englands_dreaming.jpeg$seed$::text, $seed$https://www.penguinlibros.com/es/arte-cine-y-musica/37269-libro-england-s-dreaming-9788416709656$seed$::text, $seed$B-4.893-2017$seed$::text, $seed$https://www.penguinlibros.com/es/11353-random-house$seed$::text, $seed$Sex Pistols$seed$::text, $seed$Sean infantiles. Sean irresponsables. Sean irrespetuosos. Sean todo lo que esta sociedad detesta.»Del manifiesto de los Sex Pistols

England's Dreaming es el ensayo más importante sobre el movimiento punk, sus progenitores, los Sex Pistols, y su época: los años setenta en Inglaterra. Repleto de anécdotas, de entrevistas inéditas y en exclusiva, relata la historia del meteórico ascenso y la fulminante caída de la última banda de rock´n´roll, los Sex Pistols.

Jon Savage se sitúa en el momento en que el sueño imperial inglés comenzó a mostrar sus fisuras y la subcultura se volvió el mejor lugar de resistencia. Adentrándose en el Londres más underground, este libro mezcla la teoría con la peripecia cotidiana para mostrar la metamorfosis de la identidad inglesa, y lo hace a partir de la piedra de toque de su transformación: la música punk.$seed$::text),
  (30, $seed$Mi vida al volante$seed$::text, $seed$Biografía$seed$::text, $seed$Abel Debritto$seed$::text, $seed$978-84-15996-79-8$seed$::text, $seed$neil_young.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/special-deluxe-mi-vida-al-volante/978-84-15996-79-8$seed$::text, $seed$B-4739-2015$seed$::text, $seed$https://malpasoycia.es/categoria-producto/malpaso/$seed$::text, $seed$Neil Young$seed$::text, $seed$"El sueño de un hippie", primera incursión de Neil Young en sus recuerdos, despertó entusiasmos sin fronteras. "Una obra magnífica: humilde, sincera, divertida y, a menudo, conmovedora", opinó el Wall Street Journal. "Tan fascinante y excéntrica como las propias composiciones de su autor", sentención el New York Times. El gran cantante canadiense vuelve ahora a la carga con una segunda y no menos formidable entrega donde recrea su infancia, sus experimentos musicales, sus experiencias sexuales, su vida familiar, el gallinero del rock y, por supuesto, el más tenaz de sus muchos trastornos: los coches. Éstos, en realidad, constituyen el hilo conductor y la excusa de una gira febril por las carreteras del pasado.

Automóviles clásicos y a menudo maltrechos que lo esperaban en cualquier esquina para provocar un amor súbito y una compra a quemarropa. Cada uno evoca aventuras o desventuras que, gracias a ellos, aparcan finalmente entre las páginas de un libro. Sus motores hablan, cuentan historias y "desatan la memoria: nada los detiene cuando levantas el freno".

"Special Deluxe" caputra la auténtica voz, sin duda la más lírica, de una figura singular, de una leyenda en ejercicio que es además un enigma. En esta oda a la combustión interna hallará el lector una extraordinaria miscelánea de pasiones y extravagancias, triunfos y derrotas, corduras y desvaríos... Hallará, lisa y llanamente, a un tipo asombroso llamado Neil Percival Young.$seed$::text),
  (31, $seed$Memorias$seed$::text, $seed$Biografía$seed$::text, null::text, $seed$978-84-16665-65-5$seed$::text, $seed$dylan.jpeg$seed$::text, $seed$https://malpasoycia.es/libreria/bob-dylan-cronicas-i-memorias$seed$::text, $seed$B-24392-2016$seed$::text, $seed$https://malpasoycia.es/categoria-producto/malpaso/$seed$::text, $seed$Bob Dylan$seed$::text, $seed$Bob Dylan Crónicas I. Memorias. En 1961 Bob Dylan llega a Nueva York y se instala en Greenwich Village dispuesto a encontrarse con Woody Guthrie, que por aquel entonces era el cantautor al que intentaba emular.

El joven Dylan se busca la vida tocando en distintos locales mientras vive una gran historia de amor y se desarrolla como autor.

Esa entrada en el mundo de la música profesional, que culminará en 1962 con su primer contrato discográfico, es el trasfondo de ‘Crónicas I’, un libro que recoge impresiones, vivencias y reflexiones, que presenta al primer Bob Dylan como un creador animado por una inquietud infinita.

Si conocíamos la calidad de Dylan como poeta, ‘Crónicas I’ nos descubre a un narrador extraordinario, capaz de alternar el recuerdo, lo elegíaco y las observaciones más mordaces e incisivas.$seed$::text),
  (32, $seed$Eels$seed$::text, $seed$Biografía$seed$::text, $seed$Pablo Alvarez Ellacuria$seed$::text, $seed$978-84-937362-1-7$seed$::text, $seed$eels.jpeg$seed$::text, $seed$https://blackiebooks.org/catalogo/cosas-que-los-nietos-deberian-saber-nueva-edicion/$seed$::text, $seed$B-42862-2009$seed$::text, $seed$https://blackiebooks.org$seed$::text, $seed$eels, Mark Oliver Everett$seed$::text, $seed$«Cómo afrontarla. ¿Conoces la sensación? ¿Cuando algo es demasiado hermoso? ¿Cuando alguien dice algo o escribe algo o toca algo que te conmueve hasta las lágrimas, o que llega incluso a cambiarte?» .

Mark Oliver Everett es el cantante de la banda Eels. Su vida ha sido asombrosa. También su manera de hacerle frente. Desde la muerte de su padre, el físico cuántico Hugh Everett, hasta la de su prima, que viajaba en un avión del 11S o la de su hermana, que se suicidó. También la carrera de ese chico tímido que se convirtió en uno de los grandes músicos de culto de EE. UU. «Cosas que los nietos deberían saber», su libro de memorias, es uno de los libros musicales más vendidos de la historia de la edición en nuestro país.$seed$::text),
  (33, $seed$Loco$seed$::text, $seed$Biografía$seed$::text, null::text, $seed$978-84-945916-0-0$seed$::text, $seed$loco.jpeg$seed$::text, $seed$https://www.casadellibro.com/libro-loco-como-no-llevar-un-estudio-de-grabacion/9788494591600/4161712$seed$::text, $seed$B-17.620-2016$seed$::text, $seed$Hurtado & Ortega$seed$::text, $seed$Paco Loco$seed$::text, $seed$PACO LOCO ES NUESTRO productor musical más emblemático. Es nuestro Phil Spector. Grammy nominated, columnista ocasional, víctima de un síndrome de Audiógenes incurable, Paco Loco nos abre las puertas de su estudio y nos invita a descubrir los secretos de su sabiduría chiflada y de sus míticas grabaciones. Conoceremos a Muni, pero también a Hiss & Hum; huiremos de coches que explotan; entenderemos lo de los ruidos que no se oyen, pero sí que se escuchan; aprenderemos cómo se puede ser un yonqui de lo retro y afirmar que el futuro es el pasado y que hay que volver al cassette y que lo peor es la rutina (Turner) y que los Pactos Locos (Donald, Lucas) es un gran nombre de grupo y que… Hay que leer este libro que cuenta con la participación de algunos de los nombres más significativos del panorama musical: Muni Camón, Nacho Vegas, Fran Nixon, Joaquín Pascual, John Agnello, Paco Neuman, Steve Wynn, Mikel Erentxun, David Carabén, Juan Santaner, Pedro Vigil, Miguel Fuentes, Pablo Errea, Josh Rouse, Gary Louris…$seed$::text),
  (34, $seed$The Hacienda$seed$::text, $seed$Biografía$seed$::text, $seed$Federico Corriente$seed$::text, $seed$978-84-949684-4-0$seed$::text, $seed$the_hacienda.jpeg$seed$::text, $seed$https://editorialcontra.com/producto/the-hacienda-como-no-dirigir-un-club$seed$::text, $seed$B-3803-2019$seed$::text, $seed$https://editorialcontra.com$seed$::text, $seed$Peter Hook$seed$::text, $seed$Tras el suicidio de Ian Curtis en 1980, los componentes de Joy Division se reagruparon para formar New Order, bajo el auspicio de su mánager, el carismático Rob Gretton. Durante las giras norteamericanas que cimentarían el éxito del grupo en EE.UU., descubrieron fascinados la emergente escena de clubs neoyorquina, con los míticos Danceteria y Paradise Garage a la cabeza. El excéntrico Tony Wilson, máximo responsable de Factory, el sello discográfico de Manchester que labró su éxito gracias, sobre todo, a Joy Division y New Order, decidió emprender con Gretton, arrastrando, de paso, a New Order, una ambiciosa reforma del International Marine Center para reconvertirlo en el que debía ser el club más elegante y sofisticado del mundo, a imagen y semejanza de los que habían visto en Nueva York. Para ello, contrataron al visionario arquitecto Ben Kelly, que transformó el espacio en una catedral de acero y cristal a la que llamaron The Haçienda, y que incluso recibió un número de referencia: FAC 51.

Peter Hook, cuyas líneas de bajo en Joy Division y New Order son un referente de la música popular, narra con humor y un ritmo endiablado su experiencia no solo como bajista de dos de los grupos fundamentales del rock británico sino también como copropietario a la fuerza de uno de los clubs más influyentes de todos los tiempos. Hooky, que vivía humildemente con veinte libras a la semana, no pudo imaginarse nunca que gran parte de sus abultados ingresos tras éxitos como «Blue Monday», «Bizarre Love Triangle» o «True Faith» se esfumarían en ese «agujero en el suelo conocido como The Haçienda», tal y como lo describió el productor Martin Hannett, que abrió sus puertas el 21 de mayo de 1982 para cambiar para siempre el rumbo de la escena de clubs del Reino Unido. Y si bien al principio funcionó más como una sala de conciertos —allí dieron bolos antológicos grupos como los Smiths, Happy Mondays o Stone Roses—, a partir de 1984, DJs como Mike Pickering y sus noches Nude tomaron el testigo y empezaron a pinchar una ecléctica mezcla de funk, primigenia música electrónica e indie que revolucionaron la escena musical y plantaron las semillas del fenómeno que se conoció como Madchester. Para que la revolución acabara de estallar, ya solo quedó el advenimiento del Segundo Verano del Amor, de inspiración ibicenca, que dio lugar en 1988 al apogeo de la cultura rave y al acid house.

Esta es la hilarante y desquiciada historia de The Haçienda, contada por un narrador de excepción como Peter Hook, que vio cómo la mala gestión, la violencia del crimen organizado de Manchester (rebautizada «Gunchester»), una administración pública beligerante y errores de amateur de todo tipo acabaron con la vida de un club legendario cuyo legado aún hoy pervive.$seed$::text),
  (35, $seed$Led Zepellin$seed$::text, $seed$Biografía$seed$::text, $seed$Federico Corriente$seed$::text, $seed$978-90-8998-345-9$seed$::text, $seed$led_zeppelin.jpeg$seed$::text, $seed$https://www.elargonauta.com/libros/led-zeppelin-la-historia-ilustrada-de-la-banda-de-rock-mas-sonada-de-todos-los-tiempos/978-90-8998-345-9$seed$::text, null::text, $seed$Librero b.v$seed$::text, $seed$Led Zeppelin$seed$::text, $seed$Los Led Zeppelin fueron la banda de rock por excelencia, el molde a partir del que se formó todo un género musical y, por ende, un punto de referencia para una generación y sus hijos. Este homenaje estelar cuenta con la participación de los mejores periodistas actuales especializados en rock ?de medios de la importancia de Rolling Stone, CREEM y Billboard?, así como con reflexiones sobre la influencia en la banda de otros grandes intérpretes del rock, incluidos miembros de los Kinks, Aerosmith, Heart, Mott the Hoople, los Minutemen y los Hold Steady.

Numerosas instantáneas de gloriosos conciertos y escenas fuera del escenario de algunos de los más grandes nombres de la fotografía del rock acompañan la narración de la trayectoria de la banda desde sus primeras actuaciones en 1968, como The New Yardbirds, hasta el reencuentro de 2007. También se incluye la reproducción de 450 carteles de conciertos poco difundidos, pases para la zona de bastidores, entradas de actuaciones, cubiertas de LP, singles, camisetas, chapas, etc., procedentes de Estados Unidos, Reino Unido, Europa y Japón. Una lista de la discografía y los itinerarios de las giras completa este libro, tan épico como la propia banda.

Creado de las cenizas de The Yardbirds por el guitarrista y virtuoso del estudio Jimmy Page, el grupo Led Zeppelin unió al magnífico bajista John Paul Jones, al extraordinario batería John Bonham y a Robert Plant, un vocalista sin parangón hasta entonces. La banda definió por sí misma lo que podía llegar a ser el rock and roll, y dejó a su paso una estela de leyendas tan extensa y tan real como quisimos que fuera.$seed$::text),
  (36, $seed$Mick Rock-Exposed$seed$::text, $seed$Biografía$seed$::text, $seed$Tom Stoppard$seed$::text, $seed$9780957148345$seed$::text, $seed$mick_rock.jpeg$seed$::text, $seed$https://www.palazzoeditions.com/adult-titles/mick-rock$seed$::text, null::text, $seed$https://www.palazzoeditions.com$seed$::text, $seed$Mick Rock$seed$::text, $seed$Mick Rock es el fotógrafo de rock más destacado de su generación. En "Exposed", revela su colección definitiva de imágenes, contando la historia con sus propias palabras de sus inicios profesionales y de los personajes más grandes que la vida con los que se mezcló.

Además de ser una retrospectiva de su obra, es un viaje cultural a través de una época en la que el rock reinaba. Es un compendio de experiencias, relatos de testigos oculares y detalles íntimos, todo culminando en perspicaces insights visuales incidentales y en imágenes icónicas probadas por el tiempo que todos reconocemos hoy. Este es un relato vívido y memorable de las aventuras de Rock detrás de la cámara, una colorida mezcla de lo manifiesto y lo íntimo, lo hermoso y lo irreverente, verdaderamente expuesto.$seed$::text),
  (37, $seed$The Storyteller$seed$::text, $seed$Biografía$seed$::text, $seed$Dave Grohl$seed$::text, null::text, $seed$dave_grohl.jpeg$seed$::text, $seed$https://www.amazon.es/Storyteller-Historias-vida-música-ebook/dp/B09QHY34KN/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1699127065&sr=8-2$seed$::text, null::text, null::text, $seed$Dave Grohl$seed$::text, $seed$Por suerte, mi memoria se ha mantenido relativamente intacta. Desde pequeño, siempre he medido mi vida en avances musicales, y no en meses o años. Para recordar un momento y un lugar en concreto, mi mente vuela a canciones, álbumes y bandas. Desde las emisoras AM de los setenta hasta cada uno de los micrófonos que he usado, te puedo ir diciendo el qué, el quién, el dónde y el cuándo desde las primeras notas de cualquier canción que haya saltado de un altavoz a mi alma. O de mi alma al altavoz. Para algunas personas, el detonante de un recuerdo es un sabor, para otras puede ser un olor o algo que vean. Mi detonante es el sonido, como un recopilatorio inacabado a la espera de ser enviado.

Aunque nunca he sido de los que coleccionan «cosas», sí colecciono momentos. En ese sentido, mi vida pasa ante mis ojos y a través de mis oídos todos los días. En este libro he tratado de reflejar algunos de esos momentos lo mejor que he podido. Por supuesto, esos recuerdos están llenos de música. Y a veces pueden ser ruidosos.

En The Storyteller, una colección de momentos de todas las épocas de su vida, Dave Grohl nos ofrece algo extraordinario: un retrato crudo y sincero de una vida excepcional hecha a base de momentos normales y corrientes. Cuando nos habla del amor visceral por la música y sus compañeros, de su profunda conexión con su ciudad natal, Springfield (Virginia), y del asombro con el que ve crecer a sus hijas, Dave Grohl nos cuenta sus recuerdos del mismo modo en que escribe sus canciones, desde lo más hondo de su alma. Repleto de reflexiones sobre sus giras con los Scream, su entrada en Nirvana y el desmoronamiento del grupo, la creación de los Foo Fighters cuando se encontraba en un momento decisivo de su vida y cómo ahora recorre el mundo como un padre de familia, The Storyteller son unas memorias llenas de vida y humor en las que Dave nos transmite su lúcida visión de la fama.$seed$::text),
  (38, $seed$Macro festivales$seed$::text, $seed$Análisis$seed$::text, $seed$Nando Cruz$seed$::text, null::text, $seed$macro_festivales.jpeg$seed$::text, $seed$https://www.amazon.es/Macrofestivales-agujero-negro-música-PENINSULA-ebook/dp/B0BXXLQ1RC/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1699127293&sr=8-1$seed$::text, null::text, null::text, null::text, $seed$Los grandes festivales se han convertido en un fenómeno que trasciende la propia música, cuando no contribuye directamente a su estrangulamiento. Mueven miles de millones de euros, atraen turismo, exigen subvenciones, blanquean marcas, explotan a artistas y trabajadores y saquean al público. Aun así, no hay ciudad, grande o pequeña, que no apueste por el suyo. Nando Cruz disecciona en este libro una industria que ha crecido hasta desbordarse y nos sumerge en su historia y entresijos para entender que hay detrás de ese fin de semana bucólico de confetis, pulseras, luces y conciertos.$seed$::text),
  (39, $seed$Tom Petty$seed$::text, $seed$Biografía$seed$::text, $seed$Warren Zanes$seed$::text, $seed$978-84-15887-21-8$seed$::text, $seed$petty.jpeg$seed$::text, $seed$https://www.alfaomega.es/libros/?texto=petty&action=busqueda_rapida$seed$::text, $seed$M.381-2018$seed$::text, $seed$https://www.alfaomega.es$seed$::text, $seed$Tom Petty$seed$::text, $seed$Petty nació en Gainesville, Florida, con mucha sangre sureña en las venas. A pesar de crecer en un ambiente rural cerrado que parecía ofrecerle un futuro poco prometedor, el rock and roll cambió su destino. Conoció a Elvis, vio la primera aparición de los Beatles en la TV estadounidense, fue productor de Del Shannon, formó una banda con George Harrison, Bob Dylan, Roy Orbison y Jeff Lynne, grabó discos con Johnny Cash y colocó docenas de sus propias composiciones en lo más alto de las listas de ventas. La vida de Tom Petty es una auténtica historia épica del rock and roll.

Hasta el momento de su repentino fallecimiento el 2 de octubre de 2017, a la edad de 66 años, las grabaciones y las giras siguieron formando parte de su día a día. Aunque tenía fama de proteger su privacidad, compartió con Warren Zanes ?rockero, escritor y amigo suyo? sus experiencias y su forma de entender la vida, sus aciertos y sus errores dentro y fuera del escenario, y muchos otros detalles personales. Todo ello queda recogido en esta biografía, tan intensa como rigurosa.$seed$::text),
  (40, $seed$Bodies$seed$::text, $seed$Análisis$seed$::text, $seed$Ian Winwood$seed$::text, $seed$978-84-19234-19-3$seed$::text, $seed$bodies.jpg$seed$::text, $seed$https://www.elargonauta.com/libros/bodies-vida-y-muerte-en-la-musica/978-84-19234-19-3/$seed$::text, $seed$BI 1035-2023$seed$::text, $seed$Liburuak$seed$::text, null::text, $seed$Dinero, libertad, fans que les adoran; lxs músicxs profesionales parecen tenerlo todo, pero bajo la superficie se esconde una verdad aterradora: durante años, la industria musical ha tolerado sus muertes, adicciones y problemas de salud mental en favor del entretenimiento.

En este libro, Ian Winwood explora la reticencia de esa industria a enfrentarse a sus numerosos fracasos, y cuenta historias de primera mano junto a artistas y grupos como Foo Fighters, Green Day, Trent Reznor, Biffy Clyro, Kings of Leon, Chris Cornell, Mark Lanegan o Pearl Jam. Mucho más que un simple texto sobre bandas, Winwood dirige la historia a través de su propio colapso mental tras la espantosa muerte de su padre.

Escrito con calidez, humor, perspicacia y honestidad por uno de los profesionales más incisivos de la prensa musical británica, "Bodies" arroja luz sobre la perversidad de permitir el sufrimiento ajeno, abriendo un necesario debate sobre la naturaleza de la industria musical como una insaciable picadora de carne para almas creativas con instinto de autodestrucción. Al fin y al cabo, llevamos demasiado tiempo celebrando y fomentando el continuo daño que lxs músicxs se hacen a sí mismxs en pos del gran sueño del rock. Los meses de gira rodeadxs de neveras bien abastecidas en los camerinos cada noche, con contactos locales de guardia y los subidones de adrenalina después del concierto.

Ahora con un nuevo capítulo sobre la muerte de Taylor Hawkins -Foo Fighters- y su multitudinario concierto de recuerdo en Wembley.$seed$::text),
  (41, $seed$verdades y mentiras...$seed$::text, $seed$Análisis$seed$::text, $seed$Jose Bruno y Javier Vidal$seed$::text, $seed$978-84-18813-54-2$seed$::text, $seed$verdades_y_mentiras.png$seed$::text, $seed$https://www.edicionesoblivium.com/producto/verdades-y-mentiras-sobre-tocar-un-instrumento-de-jose-bruno-y-javier-vidal/$seed$::text, $seed$M-22679-2023$seed$::text, $seed$www.edicionesoblivium.com$seed$::text, null::text, $seed$Hay muchos y muy buenos libros sobre tocar un instrumento. Bien, este en particular trata de la aventura de tocarlos todos y en él se repasan vivencias y situaciones con las que los músicos profesionales o aficionados nos topamos en la práctica y el disfrute instrumental, encima o debajo del escenario.

Estaremos en la primera fila del concierto para mostrar sin artificios qué sucede cuando el baterista cuenta ¡1, 2, 3, 4!, se encienden los focos y el tiempo se detiene. También hurgaremos en las orejas del oyente entusiasmado para entender cómo funciona la pasión musical. Rastrearemos la vocación desde sus orígenes, cuando comenzamos a emocionarnos con canciones, soñamos con nuestro primer instrumento y nos adentramos en la aventura del aprendizaje. Montaremos una banda, sin duda la parte más divertida y emocionante de todas las actividades musicales, y entraremos en el estudio de grabación para experimentar con micrófonos, emociones y divorcios que alcanzan la categoría de arte.

A la hora de defender valores estéticos, los músicos nos servimos de la inspiración, la creatividad, la improvisación, las musas, el dinero y los demonios, de cuyo manejo dependemos para llegar sanos y salvos al estribillo, y que también repasaremos buscando ese punto extra de motivación.

La lectura de este libro puede alumbrar planes futuros sin importar lo relevantes que resulten: la música siempre sorprende. Hemos mirado el mundo a través de las orejas, de la misma manera en que lo hacemos cuando comenzamos a tocar una canción, con convencimiento y expresión, viviendo la interpretación musical como un baile entre realidad y ficción, con sus grandes verdades, con sus sugerentes mentiras.$seed$::text),
  (42, $seed$Chico & Rita$seed$::text, $seed$Comic$seed$::text, $seed$Javier Mariscal y Fernando Trueba$seed$::text, $seed$978-84-96722-73-6$seed$::text, $seed$1.jpg$seed$::text, $seed$https://www.elargonauta.com/libros/chico-rita/978-84-96722-73-6$seed$::text, $seed$M-48886-2010$seed$::text, $seed$www.sinsentido.es$seed$::text, null::text, $seed$El director Fernando Trueba y el diseñador Javier Mariscal se unen en Chico & Rita para contar una hermosa historia de amor. Unidos por su común amor y admiración por la música y la cultura cubana, Trueba y Mariscal nos ofrecen una sensual recreación de una época, La Habana y Nueva York en plena efervescencia del jazz.

Adaptación de la película del mismo nombre, Chico & Rita es una novela gráfica resultado del arduo trabajo de hacer una adaptación ?a la inversa?. Esta vez es la película quien ha dado el pistoletazo de salida a la producción del libro.

El deseo inicial por hacer esta película proviene de mi amor y admiración por el trabajo de Mariscal. Para mí, Mariscal es un hijo de Picasso. Es Mediterráneo en estado puro. Es muy sensual, muy vital. Su trazo libre, la alegría de su línea, su sentido de color, sus temas ?las mujeres, el mar, el cielo, la comida? son elementos esenciales de nuestra vida, de nuestra cultura. Había soñado cómo sería una película ?pintada? íntegramente por Mariscal. Hacer juntos Chico & Rita es la materialización de ese sueño.? (Fernando Trueba)

Uno toca muchas cosas, tomas parte de tu propia vida y 90 minutos de tiempo de la gente y tenéis un diálogo. Esto no suele ser normal. Cuando trabajas con color y luz, con personajes, movimiento y voces, y esos tipos de ritmos y música, se pueden decir muchas cosas.? (Javier Mariscal, sobre el poder del cine).

En la Cuba de finales de los cuarenta, Chico y Rita inician una apasionada historia de amor. Chico es un joven pianista enamorado del jazz y Rita sueña con ser una gran cantante. Desde la noche en que el destino los junta en un baile de La Habana, la vida va uniéndolos y separándolos como a los personajes de un bolero.$seed$::text),
  (43, $seed$Bob Dylan Revisited$seed$::text, $seed$Comic$seed$::text, $seed$Varios autores$seed$::text, $seed$978-84-679-0273-0$seed$::text, $seed$2.jpeg$seed$::text, $seed$https://www.normaeditorial.com/ficha/comic-europeo/bob-dylan$seed$::text, null::text, $seed$https://www.normaeditorial.com/$seed$::text, null::text, $seed$Bob Dylan es un artista del Renacimiento. Compositor, poeta, pintor… su arte se extiende a muchas otras disciplinas, como demuestra su carrera y la infl uencia que supone para otros creadores como fotógrafos, diseñadores, escritores, cineastas… Ya era hora de que el cómic le rindiera un homenaje como es debido. 

Bob Dylan Revisited reúne 13 canciones míticas del compositor norteamericano adaptadas por 13 distintos autores de cómic. 13 versiones dibujadas para disfrutar mientras se escuchan las canciones originales, o mientras se tararean o recuerdan. 

Algunos de los dibujantes que participan son: Lorenzo Mattotti, Jean-Claude Götting, Dave McKean, Alfred, Gradimir Smudja, Benjamin Flao y Zep, entre otros.$seed$::text),
  (44, $seed$Camaron: La leyenda del genio$seed$::text, $seed$Comic$seed$::text, $seed$Sete Gonzalez$seed$::text, $seed$978-84-17858-56-8$seed$::text, $seed$3.jpg$seed$::text, $seed$https://www.planetadelibros.com/libro-camaron/307688$seed$::text, $seed$B.24.327-2019$seed$::text, $seed$https://www.planetadelibros.com/$seed$::text, null::text, $seed$Su voz desgarrada cambió la historia del flamenco. José Monje Cruz, Camarón, empezó a desplegar su don cuando era solo un niño y llegó a conquistar las audiencias de París y Nueva York. Inquieto, pasional, magnético, su arte creció imparable y revolucionario. Desde su nacimiento en San Fernando (Cádiz) hasta su temprana muerte, pasando por su estancia en Madrid, su etapa con Paco de Lucía, su boda con la Chispa, sus trabajos con Tomatito y sus conciertos más memorables, este libro es un homenaje con duende a un hombre de breve biografía pero huella infinita.$seed$::text),
  (45, $seed$Engañar al Mundo$seed$::text, $seed$Biografía$seed$::text, $seed$Josh Frank y Caryn Ganz$seed$::text, $seed$978-84-19234-10-0$seed$::text, $seed$4.jpg$seed$::text, $seed$https://www.elargonauta.com/libros/enganar-al-mundo-pixies/978-84-19234-10-0/$seed$::text, $seed$BI 00416-2023$seed$::text, $seed$https://editores-euskadi.net/editorial-liburuak/$seed$::text, null::text, $seed$Antes de que Internet, la MTV y los iPods proporcionaran a los aficionados información y comunidades lejanas -en la era pre "Never Mind"-, los jóvenes de todo el mundo crecían en un relativo aislamiento del arte creado por ellos mismos para difundir lentamente escenas y tendencias. En estas condiciones, cuatro jóvenes de Boston formaron una banda llamada Pixies.

Durante su carrera inicial de siete años, tocaron en algunos de los mejores festivales de Europa, mantuvieron a la prensa expectante y cultivaron una ferviente base de fans hambrientos de más y más. La banda trabajó rápido, produciendo cuatro álbumes a un ritmo vertiginoso, pero las presiones y los choques de personalidad pasaron factura: Pixies se disolvió justo cuando las bandas cantaban sus alabanzas como innovadores del rock&roll.$seed$::text),
  (46, $seed$Aquí vivia yo$seed$::text, $seed$Biografía$seed$::text, $seed$Joan Vich Montaner$seed$::text, $seed$978-84-19119-06-3$seed$::text, $seed$5.jpeg$seed$::text, $seed$https://www.librosdelko.com/products/aqui-vivia-yo$seed$::text, $seed$M-12659-2022$seed$::text, $seed$Libros del K.O.$seed$::text, null::text, $seed$En la primera edición del Festival Internacional de Benicàssim, celebrada en 1995, Joan Vich Montaner despachaba bebidas en una de las barras. En la última edición hasta la publicación de este libro —la de 2019—, se había convertido en codirector del célebre festival. Durante esos veinticinco años, además de haberse ocupado de otras tareas como la programación musical, fue recogiendo muchas historias que comparte en estas páginas. Algunas de ellas tienen como protagonistas a artistas célebres: Lou Reed, Morrissey, Noel Gallagher, Amy Winehouse… Pero otras tienen a personajes menos conocidos que también contribuyeron a que el FIB se convirtiera en el estandarte de los festivales españoles. Aunque este libro no es solo una recopilación de anécdotas jugosas o una aproximación —tan rigurosa como divertida— al funcionamiento de la industria musical, sino también un homenaje sincero a un evento que moldeó los gustos culturales y los veranos de muchos españoles, y un reconocimiento emotivo a la manera en la que la música se entreteje con nuestras biografías. Si has vibrado en algún festival durante el último cuarto de siglo, seguro que reconoces muchas de las emociones que describe el autor.$seed$::text),
  (47, $seed$El acto de crear: una manera de ser$seed$::text, $seed$Biografía$seed$::text, $seed$Rick Rubin$seed$::text, $seed$978-84-1119-106-7$seed$::text, $seed$6.JPG$seed$::text, $seed$https://www.planetadelibros.com/libro-el-acto-de-crear/383698$seed$::text, $seed$B.17.513-2023$seed$::text, $seed$Planeta.$seed$::text, null::text, $seed$Del legendario productor musical, un maestro en el arte de ayudar a los demás a conectar con las fuentes de su propia creatividad, llega un libro maravillosamente fraguado a lo largo de muchos años con una visión profunda de la creatividad y de la vida dirigida todo el mundo

Me propuse a mí mismo escribir un libro acerca de cómo crear una gran obra de arte. En lugar de eso, se reveló como un libro acerca de cómo Ser.Los grandes productores musicales suelen ser reconocidos por un sonido único que solo ellos son capaces de lograr. Rick Rubin es conocido por eso y por algo más: por saber crear un espacio en el que artistas de diferentes géneros y tradiciones se reencuentran con su identidad profunda y con aquello que realmente tienen que ofrecer al mundo. Rubin ha convertido en una práctica su impulso de ayudar a las personas para que trasciendan expectativas autoimpuestas y reconecten con un estado de inocencia en el que lo sorprendente se convierte en inevitable. A lo largo de los años, Rubin ha pensado mucho en el origen de la creatividad: de dónde viene y de dónde no, y ha aprendido que ser artista no depende tanto de un resultado en concreto, sino de cómo nos relacionamos con el mundo. La creatividad tiene un lugar en la vida de todas las personas y todos podemos hacer ese espacio más grande. De hecho, hay pocas responsabilidades humanas que sean más importantes que esa.

El acto de crear es un curso bello y generoso que ilumina el camino del artista como una ruta que todos podemos seguir. Este libro destila la sabiduría recogida durante el trabajo de toda una vida y la convierte en una luminosa experiencia de lectura que tiene el poder de crear momentos —y vidas— de gozo y trascendencia al alcance de todo el mundo.

«Una hermosa reflexión sobre el proceso creativo. Guia a los lectores a través de “78 áreas de pensamiento”, Rubin comparte su visión de la creatividad, que a su vez refleja su forma de ver el mundo. El libro hace un trabajo extraordinario al explicar estas ideas profundas y filosóficas de una manera fácil de entender»,$seed$::text),
  (48, $seed$Vasos Comunicantes$seed$::text, $seed$Biografía$seed$::text, $seed$Bruno Galindo$seed$::text, $seed$84-931607-7-6$seed$::text, $seed$7.JPG$seed$::text, $seed$https://brunogalindo.com/libros/vasos-comunicantes-como-y-para-que-escribir-canciones/$seed$::text, $seed$Z-80-2002$seed$::text, $seed$www.zonadeobras.com$seed$::text, null::text, $seed$Vasos comunicantes (¿Cómo y para qué escribir canciones?) es una recopilación de respuestas a esta única pregunta; declaraciones o entrevistas que sirven para explicar los secretos y técnicas de más de 200 autores de más de 40 países, y que han sido recogidas por el periodista y crítico musical Bruno Galindo en el período 1995-2001.

Entre los autores entrevistados aparecen nombres clave en la historia de la música contemporánea, nombres tan imprescindibles como David Bowie, Prince, Björk, Bono, Noel Gallagher, Iggy Pop, Antonio Vega, Thom Yorke, Joe Strummer, David Byrne, Courtney Love, Youssou N’Dour, Charly García, Khaled, John Lee Hooker, Joaquín Sabina, John Lydon, Compay Segundo, Andrés Calamaro, Perry Farrell, Brian Eno, Aretha Franklin, Manu Chao, Jarvis Cocker, Mike D, Elvis Costello, Marylin Manson, Paolo Conte, Billy Bragg, Tricky, Enrique Urquijo, Lenine, Howie B, Kiko Veneno, Julián Hernández, Paddy McAloon, Carlinhos Brown, Franco Battiato, Manolo García, Ali Farka Toure, Santiago Auserón, Silvio Rodríguez, Lauryn Hill, Pedro Guerra, Manu Dibango, Sinèad O’Connor, Neneh Cherry, Curtis Mayfield, k. d. Lang, Fito Páez, Flaco Jiménez, Herbert Vianna, Goran Bregovic, David Sylvian, Luis Eduardo Aute, Mike Scott, Cheikh Lô, Rachid Taha, Jorge Drexler, Mark Knopfler, más miembros de bandas legendarias como The Beatles, The Doors, Sex Pistols, Os Mutantes y Radio Futura, y familiares o personajes del entorno de Bob Marley y Jimi Hendrix.$seed$::text),
  (49, $seed$Nirvana: Espíritu adolescente$seed$::text, $seed$Biografía$seed$::text, $seed$David León$seed$::text, $seed$978-84-18246-09-8$seed$::text, $seed$8.jpg$seed$::text, $seed$https://www.elargonauta.com/libros/nirvana-espiritu-adolescente/978-84-18246-09-8/$seed$::text, $seed$B.3.610-2020$seed$::text, $seed$boldletters$seed$::text, null::text, $seed$La banda conocida como los reyes del "Grunge", que definió a una generación, cuya influencia llega hasta nuestros días y cuyo solista, Kurt Cobain, se convirtió en todo un icono. Tuvieron su primer gran éxito con el tema "Smells Like Teeen Spirit" que revolucionó las listas de éxitos y su música ya ha quedado inmortalizada con su admisión en el museo Rock & Roll Hall of Fame.$seed$::text),
  (50, $seed$12 notas: Quincy Jones$seed$::text, $seed$Biografía$seed$::text, $seed$Quincy Jones$seed$::text, $seed$978-84-10442-31-3$seed$::text, $seed$9.jpg$seed$::text, $seed$https://www.elargonauta.com/libros/12-notas-sobre-la-vida-y-la-creatividad/978-84-10442-31-3/$seed$::text, $seed$B-1431-2025$seed$::text, $seed$Roca Editorial de libros, S.L.U$seed$::text, null::text, $seed$12 notas es una guía de autodesarrollo que nos confirma que la creatividad es una llamada que puede y debe ser respondida sin importar la edad que tengas. A partir de su propia vida y de la de sus muchos colaboradores creativos, pasados y presentes, los lectores aprenderán lecciones, tanto filosóficas, como todo de herramientas para transformar el dolor en poder, así como recordatorios prácticos, como el valor de establecer metas y articular intenciones a traves de afirmaciones diarias. Quincy compartió su propio proceso con los lectores para que comprendan la importancia de dejar que la honestidad, el trabajo duro y las buenas relaciones, y no el ego, impulsen tu carrera.$seed$::text),
  (51, $seed$Algún tiempo atrás. La vida de Gustavo Cerati$seed$::text, $seed$Biografía$seed$::text, $seed$Sergio Marchi$seed$::text, $seed$978-950-07-6876-4$seed$::text, $seed$10.jpg$seed$::text, $seed$https://www.penguinlibros.com/es/tematicas/330387-audiolibro-algun-tiempo-atras-la-vida-de-gustavo-cerati-9789500768887$seed$::text, null::text, $seed$penguinlibros.com$seed$::text, null::text, $seed$La biografía definitiva de Gustavo Cerati, uno de los músicos argentinos de mayor trascendencia internacional, escrita por uno de los periodistas e historiadores que mejor lo conoció, y que pone en un mismo, exhaustivo tomo, hecho de infinidad de entrevistas y un enorme archivo personal, las distintas dimensiones del hombre y el artista, su recorrido vital, su fuerza creativa y su enorme legado$seed$::text)
)
insert into public.libros (
  titulo,
  categoria,
  autor,
  isbn,
  caratula,
  enlace,
  deposito_legal,
  editorial,
  protagonista,
  sinopsis
)
select
  titulo,
  categoria,
  autor,
  isbn,
  caratula,
  enlace,
  deposito_legal,
  editorial,
  protagonista,
  sinopsis
from source
order by ord;

commit;
