begin;

insert into public.grupos (nombre)
values
  ('Audioslave'),
  ('Bala'),
  ('Black Flag'),
  ('Black Sabbath'),
  ('Blind Faith'),
  ('Blondie'),
  ('Bob Marley & The Wailers'),
  ('Burning'),
  ('Cicatriz'),
  ('Coque Malla'),
  ('Corizonas'),
  ('crownledgecolektive'),
  ('Daiistar'),
  ('Dead Poet Society'),
  ('Deff Leppard'),
  ('Depeche Mode'),
  ('Dr. Feelgood'),
  ('E-Street Band'),
  ('Eskorbuto'),
  ('Eurythmics'),
  ('Extremoduro'),
  ('Fleetwood Mac'),
  ('Foo Fighters'),
  ('Fortune Child'),
  ('G3'),
  ('Gari eta maldanbera'),
  ('Genesis'),
  ('Gin Lady'),
  ('Heroes del Silencio'),
  ('Hertzainak'),
  ('Ibai García Blues Project'),
  ('Ilegales'),
  ('Iron Maiden'),
  ('Jane''s Addiction'),
  ('Jeff Beck Group'),
  ('John Mayall & The Bluesbreakers'),
  ('Joy Division'),
  ('Judas Priest'),
  ('Kabaka Pyramid'),
  ('King Crimson'),
  ('Kortatu'),
  ('Krackerjack'),
  ('Kyuss'),
  ('L7'),
  ('La Polla Records'),
  ('Leño'),
  ('Leon Benavente'),
  ('Living Colour'),
  ('Los Deltonos'),
  ('Los Enemigos'),
  ('Los Ilegales'),
  ('Los Zigarros'),
  ('MC5'),
  ('Megadeth'),
  ('Mike Farris'),
  ('Morgan'),
  ('Motorhead'),
  ('Motörhead'),
  ('Neurotic Outsiders'),
  ('Nine Inch Nails'),
  ('Niños Mutantes'),
  ('Nirvana'),
  ('Oasis'),
  ('Ojete Calor'),
  ('Pantera'),
  ('Pixies'),
  ('Placebo'),
  ('Queen'),
  ('Queen Of The Stone Age'),
  ('Quiet Riot'),
  ('Radio Futura'),
  ('Rainbow'),
  ('Ramones'),
  ('RIP'),
  ('Rozalen'),
  ('Scorpions'),
  ('Sex Museum'),
  ('Sisters of Mercy'),
  ('Slayer'),
  ('Sly and the Family Stone'),
  ('Sobrinus'),
  ('Sonic Youth'),
  ('Soundgarden'),
  ('Stone Roses'),
  ('Stray Cats'),
  ('System of a Down'),
  ('Talking Heads'),
  ('Tenacious D'),
  ('The Allman Brothers Band'),
  ('The Bangles'),
  ('The Byrds'),
  ('The Cramps'),
  ('The Cure'),
  ('The Doors'),
  ('The Eagles'),
  ('The Jam'),
  ('The Mothers of Invention'),
  ('The Pictubebooks'),
  ('The Picturebooks'),
  ('The Pixies'),
  ('The Prodigy'),
  ('The Quarrymen'),
  ('The Ramones'),
  ('The Runaways'),
  ('The Smashing Pumpkins'),
  ('The Stooges'),
  ('The Velvet Underground'),
  ('The White Stripes'),
  ('The Yardbirds'),
  ('Thin Lizzy'),
  ('Tom Petty & The Heartbreakers'),
  ('Tom Petty and the Heartbreakers'),
  ('Tool'),
  ('Twisted Sister'),
  ('Velvet Revolver')
on conflict (nombre) do nothing;

commit;
