begin;

with source (
  id,
  titulo,
  year_publicacion,
  is_in_spotify,
  etiqueta,
  caratula,
  firmado,
  grupo_id
) as (
  values
  (1::integer, 'Greens From the garden'::text, 1999::integer, true::boolean, 1::integer, null::text, null::boolean, 6::bigint),
  (2::integer, '461 ocean boulevard'::text, 1974::integer, true::boolean, 72::integer, null::text, null::boolean, 8::bigint),
  (3::integer, 'Crossroads 2'::text, 1996::integer, true::boolean, 570::integer, null::text, null::boolean, 8::bigint),
  (4::integer, 'Derek and the Dominos - Layla and other assorted love songs'::text, 1970::integer, true::boolean, 168::integer, null::text, null::boolean, 8::bigint),
  (5::integer, 'one more car one more rider'::text, 2001::integer, true::boolean, 206::integer, null::text, null::boolean, 8::bigint),
  (6::integer, 'Sessions for Robert J'::text, 2004::integer, true::boolean, 264::integer, null::text, null::boolean, 8::bigint),
  (7::integer, 'slowhand'::text, 1977::integer, true::boolean, 73::integer, null::text, null::boolean, 8::bigint),
  (8::integer, 'Unplugged'::text, 1992::integer, true::boolean, 85::integer, null::text, null::boolean, 8::bigint),
  (9::integer, 'The road to escondido'::text, 2006::integer, true::boolean, 3::integer, null::text, null::boolean, 8::bigint),
  (10::integer, 'Back in black'::text, 1980::integer, true::boolean, 39::integer, null::text, null::boolean, 11::bigint),
  (11::integer, 'Black Ice'::text, 2008::integer, true::boolean, 31::integer, null::text, null::boolean, 11::bigint),
  (12::integer, 'High Voltage'::text, 1976::integer, true::boolean, 83::integer, null::text, null::boolean, 11::bigint),
  (13::integer, 'Highway To Hell'::text, 1979::integer, true::boolean, 22::integer, null::text, null::boolean, 11::bigint),
  (14::integer, 'Live'::text, 1991::integer, true::boolean, 69::integer, null::text, null::boolean, 11::bigint),
  (15::integer, '21'::text, 2011::integer, true::boolean, 77::integer, null::text, null::boolean, 12::bigint),
  (16::integer, 'Aerosmith''s greatest hits 1973-1988'::text, 2008::integer, false::boolean, 29::integer, null::text, null::boolean, 13::bigint),
  (17::integer, 'Alice In Chains'::text, 1995::integer, true::boolean, 538::integer, null::text, null::boolean, 14::bigint),
  (18::integer, 'Back to black'::text, 2007::integer, true::boolean, 30::integer, null::text, null::boolean, 15::bigint),
  (19::integer, 'East of electric'::text, 2008::integer, true::boolean, 41::integer, null::text, null::boolean, 16::bigint),
  (20::integer, 'Live: Ballad of an outlaw women'::text, 2001::integer, false::boolean, 42::integer, null::text, null::boolean, 16::bigint),
  (21::integer, 'Solo Rot'::text, 2010::integer, true::boolean, 78::integer, null::text, true::boolean, 17::bigint),
  (22::integer, 'Jackie Brown (B.S.O.)'::text, 1997::integer, true::boolean, 164::integer, null::text, null::boolean, 18::bigint),
  (23::integer, 'Licensed To ill'::text, 1986::integer, true::boolean, 490::integer, null::text, null::boolean, 19::bigint),
  (24::integer, 'Both sides of the gun'::text, 2006::integer, true::boolean, 51::integer, null::text, null::boolean, 20::bigint),
  (25::integer, 'Diamonds on the inside'::text, 2003::integer, true::boolean, 54::integer, null::text, null::boolean, 20::bigint),
  (26::integer, 'Fight Four Your Mind'::text, 1995::integer, true::boolean, 563::integer, null::text, null::boolean, 20::bigint),
  (27::integer, 'give till it''s gone'::text, 2011::integer, true::boolean, 82::integer, null::text, null::boolean, 20::bigint),
  (28::integer, 'Lifeline'::text, 2007::integer, true::boolean, 4::integer, null::text, null::boolean, 20::bigint),
  (29::integer, 'Live From Mars'::text, 2001::integer, true::boolean, 553::integer, null::text, null::boolean, 20::bigint),
  (30::integer, 'Live from Montreal International Jazz Festival'::text, 2010::integer, false::boolean, 66::integer, null::text, null::boolean, 20::bigint),
  (31::integer, 'There will be a light'::text, 2004::integer, true::boolean, 260::integer, null::text, null::boolean, 20::bigint),
  (32::integer, 'White lies for dark times'::text, 2009::integer, true::boolean, 34::integer, null::text, null::boolean, 20::bigint),
  (33::integer, 'Modern Times'::text, 2006::integer, true::boolean, 18::integer, null::text, null::boolean, 21::bigint),
  (34::integer, 'Street-Legal'::text, 1978::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (35::integer, 'Pat Garret & Billy the Kid'::text, 1973::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (36::integer, 'Highway 61 Revisited'::text, 1965::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (37::integer, 'The bootleg series Vol. 4'::text, 1966::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (38::integer, 'Bob Dylan'::text, 1962::integer, false::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (39::integer, 'The bootleg series Vol. 5'::text, 1975::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (40::integer, 'New Morning'::text, 1970::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (41::integer, 'Hard Rain'::text, 1976::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (42::integer, 'Another side of Bob Dylan'::text, 1964::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (43::integer, 'The bootleg series Vol. 6'::text, 1964::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (44::integer, 'Blonde on Blonde'::text, 1966::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (45::integer, 'The bootleg series Vol. 1-3'::text, 1961::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (46::integer, 'Blood on the tracks'::text, 1975::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (47::integer, 'Planet waves'::text, 1974::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (48::integer, 'At Budokan (I)'::text, 1978::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (49::integer, 'At Budokan (II)'::text, 1978::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (50::integer, 'The Freewheelin'''::text, 1963::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (51::integer, 'Nashville Skyline'::text, 1969::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (52::integer, 'The times they are a-changin'''::text, 1964::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (53::integer, 'Bringing it all back home'::text, 1965::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (54::integer, 'John Wesley harding'::text, 1967::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (55::integer, 'Selfportrait'::text, 1970::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (56::integer, 'The bootleg series Vol. 7 (No direction home soundtrack)'::text, 1961::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (57::integer, 'Desire'::text, 1976::integer, true::boolean, 0::integer, null::text, null::boolean, 21::bigint),
  (58::integer, 'Born in the USA'::text, 1984::integer, true::boolean, 45::integer, null::text, null::boolean, 22::bigint),
  (59::integer, 'Born to run'::text, 1975::integer, true::boolean, 21::integer, null::text, null::boolean, 22::bigint),
  (60::integer, 'Devils & Dust'::text, 2005::integer, true::boolean, 44::integer, null::text, null::boolean, 22::bigint),
  (61::integer, 'Magic'::text, 2007::integer, true::boolean, 10::integer, null::text, null::boolean, 22::bigint),
  (62::integer, 'The Rising'::text, 2002::integer, true::boolean, 9::integer, null::text, null::boolean, 22::bigint),
  (63::integer, 'Adrenalina & Distorsión'::text, 2002::integer, false::boolean, 678::integer, null::text, null::boolean, 23::bigint),
  (64::integer, 'Our man in Paris'::text, 1963::integer, true::boolean, 0::integer, null::text, null::boolean, 24::bigint),
  (65::integer, 'Birth of the cool'::text, 2000::integer, true::boolean, 0::integer, null::text, null::boolean, 25::bigint),
  (66::integer, 'Newk''s time'::text, 2004::integer, true::boolean, 0::integer, null::text, null::boolean, 26::bigint),
  (67::integer, 'Midnight Blue'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 27::bigint),
  (68::integer, 'Genius of modern music'::text, 2001::integer, true::boolean, 0::integer, null::text, null::boolean, 28::bigint),
  (69::integer, 'Page one'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 29::bigint),
  (70::integer, 'Something'' else'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 30::bigint),
  (71::integer, 'At storyville'::text, 1988::integer, true::boolean, 0::integer, null::text, null::boolean, 31::bigint),
  (72::integer, 'Now he sings, now he sobs'::text, 2002::integer, true::boolean, 0::integer, null::text, null::boolean, 32::bigint),
  (73::integer, 'Undercurrent'::text, 2002::integer, true::boolean, 0::integer, null::text, null::boolean, 33::bigint),
  (74::integer, 'The roadside kind'::text, 2018::integer, true::boolean, 0::integer, null::text, null::boolean, 34::bigint),
  (75::integer, 'First Round'::text, 2016::integer, false::boolean, 0::integer, null::text, null::boolean, 35::bigint),
  (76::integer, 'The takeoff'::text, 2017::integer, false::boolean, 0::integer, null::text, null::boolean, 36::bigint),
  (77::integer, 'The all-time greatest hits of'::text, 1974::integer, true::boolean, 0::integer, null::text, null::boolean, 37::bigint),
  (78::integer, 'La luz en tus entrañas'::text, 1990::integer, true::boolean, 0::integer, null::text, null::boolean, 38::bigint),
  (79::integer, 'Duets'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 39::bigint),
  (80::integer, 'Moanin'''::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 40::bigint),
  (81::integer, 'Maiden Voyage'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 41::bigint),
  (82::integer, 'Money Jungle'::text, 2002::integer, true::boolean, 0::integer, null::text, null::boolean, 42::bigint),
  (83::integer, 'Speak no evil'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 43::bigint),
  (84::integer, 'Song for my father'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 44::bigint),
  (85::integer, 'The sidewinder'::text, 1999::integer, true::boolean, 0::integer, null::text, null::boolean, 45::bigint),
  (86::integer, 'Blue Train'::text, 2003::integer, true::boolean, 0::integer, null::text, null::boolean, 46::bigint),
  (87::integer, 'Dos amigos, un siglo de música'::text, 2016::integer, true::boolean, 0::integer, null::text, null::boolean, 47::bigint),
  (88::integer, 'Back at the chicken shack'::text, 1960::integer, true::boolean, 0::integer, null::text, null::boolean, 48::bigint),
  (89::integer, 'Billie''s Blues'::text, 1988::integer, true::boolean, 0::integer, null::text, null::boolean, 49::bigint),
  (90::integer, 'Chez Luna'::text, 2011::integer, true::boolean, 88::integer, null::text, null::boolean, 50::bigint),
  (91::integer, 'Viva la vida or death and all his friends'::text, 2008::integer, true::boolean, 25::integer, null::text, null::boolean, 51::bigint),
  (92::integer, 'X&Y'::text, 2005::integer, true::boolean, 291::integer, null::text, null::boolean, 51::bigint),
  (93::integer, 'Disciplined Breakdown'::text, 1997::integer, true::boolean, 569::integer, null::text, null::boolean, 52::bigint),
  (94::integer, 'Wheels of fire'::text, 1968::integer, true::boolean, 95::integer, null::text, null::boolean, 53::bigint),
  (95::integer, 'Big whiskey & the groogrux king'::text, 2009::integer, true::boolean, 47::integer, null::text, null::boolean, 54::bigint),
  (96::integer, 'Everyday'::text, 2001::integer, true::boolean, 539::integer, null::text, null::boolean, 54::bigint),
  (97::integer, 'Recently'::text, 1994::integer, true::boolean, 568::integer, null::text, null::boolean, 54::bigint),
  (98::integer, 'Stand Up'::text, 2005::integer, true::boolean, 14::integer, null::text, null::boolean, 54::bigint),
  (99::integer, 'Deepest Purple'::text, 1980::integer, true::boolean, 94::integer, null::text, null::boolean, 55::bigint),
  (100::integer, 'Machine Head'::text, 1997::integer, true::boolean, 99::integer, null::text, null::boolean, 55::bigint),
  (101::integer, 'The best of Delamitri hatful of rain'::text, 1998::integer, true::boolean, 277::integer, null::text, null::boolean, 56::bigint),
  (102::integer, 'The look of love'::text, 2001::integer, true::boolean, 148::integer, null::text, null::boolean, 57::bigint),
  (103::integer, 'Brothers in arms'::text, 1996::integer, true::boolean, 545::integer, null::text, null::boolean, 58::bigint),
  (104::integer, 'Alchemy'::text, 1984::integer, true::boolean, 165::integer, null::text, null::boolean, 58::bigint),
  (105::integer, 'Live scenes from New York'::text, 2001::integer, true::boolean, 602::integer, null::text, null::boolean, 59::bigint),
  (106::integer, 'Out there'::text, 2006::integer, true::boolean, 5::integer, null::text, null::boolean, 60::bigint),
  (107::integer, 'NBC TV Special'::text, 1968::integer, true::boolean, 46::integer, null::text, null::boolean, 61::bigint),
  (108::integer, 'The Gospel Masters'::text, 2009::integer, false::boolean, 86::integer, null::text, null::boolean, 61::bigint),
  (109::integer, 'Forever everlasting'::text, 1989::integer, true::boolean, 267::integer, null::text, null::boolean, 62::bigint),
  (110::integer, 'Angel Dust'::text, 1992::integer, true::boolean, 26::integer, null::text, null::boolean, 63::bigint),
  (111::integer, 'The Real Thing'::text, 1989::integer, true::boolean, 26::integer, null::text, null::boolean, 63::bigint),
  (112::integer, 'Classic Sinatra - His Greatest Hits'::text, 1950::integer, false::boolean, 32::integer, null::text, null::boolean, 64::bigint),
  (113::integer, 'my way the best of sinatra'::text, 1997::integer, false::boolean, 35::integer, null::text, null::boolean, 64::bigint),
  (114::integer, 'Cheap Thrills'::text, 1998::integer, true::boolean, 566::integer, null::text, null::boolean, 65::bigint),
  (115::integer, 'Hot Rats'::text, 1969::integer, true::boolean, 147::integer, null::text, null::boolean, 65::bigint),
  (116::integer, 'The Action Is Go'::text, 1997::integer, true::boolean, 60::integer, null::text, null::boolean, 66::bigint),
  (117::integer, 'America eats its young'::text, 1972::integer, true::boolean, 138::integer, null::text, null::boolean, 67::bigint),
  (118::integer, 'Standing on the verge of getting it on'::text, 1974::integer, true::boolean, 119::integer, null::text, null::boolean, 67::bigint),
  (119::integer, '16 lore'::text, 2009::integer, true::boolean, 56::integer, null::text, null::boolean, 68::bigint),
  (120::integer, 'Out in the fields-The very best of'::text, 1998::integer, true::boolean, 383::integer, null::text, null::boolean, 69::bigint),
  (121::integer, 'The best of Gerry Rafferty'::text, 1997::integer, true::boolean, 111::integer, null::text, null::boolean, 70::bigint),
  (122::integer, 'Live…With a Little Help From Our Friends'::text, 1999::integer, true::boolean, 676::integer, null::text, null::boolean, 71::bigint),
  (123::integer, 'Appetite For Destruction'::text, 1987::integer, true::boolean, 167::integer, null::text, null::boolean, 72::bigint),
  (124::integer, 'Color me'::text, 2001::integer, false::boolean, 623::integer, null::text, null::boolean, 73::bigint),
  (125::integer, 'Grace'::text, 1994::integer, true::boolean, 24::integer, null::text, null::boolean, 74::bigint),
  (126::integer, 'Mystery White Boy'::text, 1994::integer, true::boolean, 24::integer, null::text, null::boolean, 74::bigint),
  (127::integer, 'Greatest Hits'::text, 1997::integer, true::boolean, 322::integer, null::text, null::boolean, 75::bigint),
  (128::integer, 'Living In The Past'::text, 1972::integer, true::boolean, 171::integer, null::text, null::boolean, 75::bigint),
  (129::integer, 'Are You Experienced'::text, 1967::integer, true::boolean, 313::integer, null::text, null::boolean, 76::bigint),
  (130::integer, 'Blues'::text, 1984::integer, true::boolean, 320::integer, null::text, null::boolean, 76::bigint),
  (131::integer, 'Electric Ladyland'::text, 1968::integer, true::boolean, 312::integer, null::text, null::boolean, 76::bigint),
  (132::integer, 'Live at The Greek'::text, 1999::integer, true::boolean, 316::integer, null::text, null::boolean, 77::bigint),
  (133::integer, 'Joe Satriani'::text, 1995::integer, true::boolean, 239::integer, null::text, null::boolean, 78::bigint),
  (134::integer, 'Strange beautiful music'::text, 2002::integer, true::boolean, 689::integer, null::text, null::boolean, 78::bigint),
  (135::integer, 'John Mayall & Blues Breakers with Eric Clapton'::text, 1966::integer, false::boolean, 675::integer, null::text, null::boolean, 79::bigint),
  (136::integer, 'Room for squares'::text, 2001::integer, true::boolean, 57::integer, null::text, null::boolean, 80::bigint),
  (137::integer, 'Friday night in San Francisco'::text, 1981::integer, true::boolean, 230::integer, null::text, null::boolean, 81::bigint),
  (138::integer, 'Hopes and fears'::text, 2004::integer, true::boolean, 309::integer, null::text, null::boolean, 82::bigint),
  (139::integer, 'Main Offender'::text, 1992::integer, true::boolean, 658::integer, null::text, null::boolean, 83::bigint),
  (140::integer, 'Coast2Coast'::text, 2006::integer, false::boolean, 7::integer, null::text, null::boolean, 84::bigint),
  (141::integer, 'The history of rock'::text, 2000::integer, false::boolean, 266::integer, null::text, null::boolean, 85::bigint),
  (142::integer, 'Alive II'::text, 1977::integer, true::boolean, 359::integer, null::text, null::boolean, 86::bigint),
  (143::integer, 'Creatures of the Night'::text, 1982::integer, true::boolean, 330::integer, null::text, null::boolean, 86::bigint),
  (144::integer, 'Eye to the telescope'::text, 2004::integer, false::boolean, 297::integer, null::text, null::boolean, 87::bigint),
  (145::integer, 'Kukuma'::text, 2004::integer, true::boolean, 212::integer, null::text, null::boolean, 88::bigint),
  (146::integer, 'III'::text, 1970::integer, true::boolean, 68::integer, null::text, null::boolean, 10::bigint),
  (147::integer, 'IV'::text, 1971::integer, true::boolean, 243::integer, null::text, null::boolean, 10::bigint),
  (148::integer, 'Led Zeppelin'::text, 1968::integer, true::boolean, 175::integer, null::text, null::boolean, 10::bigint),
  (149::integer, 'Led Zeppelin II'::text, 1969::integer, true::boolean, 174::integer, null::text, null::boolean, 10::bigint),
  (150::integer, 'Physical Graffiti'::text, 1975::integer, true::boolean, 173::integer, null::text, null::boolean, 10::bigint),
  (151::integer, 'Remasters'::text, 1990::integer, true::boolean, 244::integer, null::text, null::boolean, 10::bigint),
  (152::integer, 'Kind of blue'::text, 1959::integer, true::boolean, 40::integer, null::text, null::boolean, 25::bigint),
  (153::integer, 'back spacer'::text, 2009::integer, true::boolean, 52::integer, null::text, null::boolean, 7::bigint),
  (154::integer, 'Pearl Jam'::text, 2006::integer, true::boolean, 52::integer, null::text, null::boolean, 7::bigint),
  (155::integer, 'Ten'::text, 1992::integer, true::boolean, 11::integer, null::text, null::boolean, 7::bigint),
  (156::integer, 'Abbey Road'::text, 1969::integer, true::boolean, 59::integer, null::text, null::boolean, 1::bigint),
  (157::integer, 'Revolver'::text, 1966::integer, true::boolean, 134::integer, null::text, null::boolean, 1::bigint),
  (158::integer, 'Sgt. Pepper`s Lonely hearts club band'::text, 1967::integer, true::boolean, 130::integer, null::text, null::boolean, 1::bigint),
  (159::integer, 'Exile on main street'::text, 1972::integer, true::boolean, 74::integer, null::text, null::boolean, 2::bigint),
  (160::integer, 'Stripped'::text, 1995::integer, true::boolean, 503::integer, null::text, null::boolean, 2::bigint),
  (161::integer, 'Tatoo You'::text, 1981::integer, true::boolean, 323::integer, null::text, null::boolean, 2::bigint),
  (162::integer, 'Vodoo Lounge'::text, 1994::integer, true::boolean, 324::integer, null::text, null::boolean, 2::bigint),
  (163::integer, 'Mama Said'::text, 1991::integer, true::boolean, 299::integer, null::text, null::boolean, 89::bigint),
  (164::integer, 'Postcards from heaven'::text, 1997::integer, true::boolean, 299::integer, null::text, null::boolean, 90::bigint),
  (165::integer, 'Birds of pray'::text, 2003::integer, true::boolean, 116::integer, null::text, null::boolean, 91::bigint),
  (166::integer, 'V'::text, 2001::integer, true::boolean, 577::integer, null::text, null::boolean, 91::bigint),
  (167::integer, 'The Orchard'::text, 2008::integer, true::boolean, 15::integer, null::text, null::boolean, 92::bigint),
  (168::integer, 'NYC Man'::text, 2003::integer, true::boolean, 84::integer, null::text, null::boolean, 93::bigint),
  (169::integer, 'Ella & Louis'::text, 1957::integer, true::boolean, 33::integer, null::text, null::boolean, 94::bigint),
  (170::integer, 'O Son Do Ar'::text, 1997::integer, true::boolean, 271::integer, null::text, null::boolean, 95::bigint),
  (171::integer, 'Lynch Mob'::text, 1992::integer, true::boolean, 249::integer, null::text, null::boolean, 96::bigint),
  (172::integer, 'A Retrospective'::text, 1993::integer, true::boolean, 250::integer, null::text, null::boolean, 97::bigint),
  (173::integer, 'Dial Maceo'::text, 2000::integer, true::boolean, 575::integer, null::text, null::boolean, 98::bigint),
  (174::integer, 'The very best of macy gray'::text, 2004::integer, true::boolean, 17::integer, null::text, null::boolean, 99::bigint),
  (175::integer, 'Angels of destruction'::text, 2008::integer, true::boolean, 16::integer, null::text, null::boolean, 100::bigint),
  (176::integer, 'Let''s cut the crap and hook up later on tonight'::text, 2004::integer, true::boolean, 36::integer, null::text, null::boolean, 100::bigint),
  (177::integer, 'What''s going on'::text, 1971::integer, true::boolean, 65::integer, null::text, null::boolean, 101::bigint),
  (178::integer, 'What did you expect?'::text, 2011::integer, true::boolean, 80::integer, null::text, null::boolean, 102::bigint),
  (179::integer, 'Bilbao BBK Live Festival, 29 Junio 2007'::text, 2007::integer, false::boolean, 28::integer, null::text, null::boolean, 103::bigint),
  (180::integer, 'Reload'::text, 1997::integer, true::boolean, 329::integer, null::text, null::boolean, 103::bigint),
  (181::integer, 'In a sea of prawns'::text, 2002::integer, true::boolean, 672::integer, null::text, null::boolean, 104::bigint),
  (182::integer, 'MHC'::text, 2007::integer, true::boolean, 13::integer, null::text, null::boolean, 104::bigint),
  (183::integer, 'sisterland'::text, 2004::integer, true::boolean, 48::integer, null::text, null::boolean, 104::bigint),
  (184::integer, 'Wito'::text, 2010::integer, true::boolean, 70::integer, null::text, null::boolean, 104::bigint),
  (185::integer, 'The day after'::text, 2012::integer, true::boolean, 89::integer, null::text, null::boolean, 104::bigint),
  (186::integer, 'Stay Free'::text, 2014::integer, true::boolean, 102::integer, null::text, null::boolean, 104::bigint),
  (187::integer, 'E=mHc2'::text, 2017::integer, true::boolean, 0::integer, null::text, null::boolean, 104::bigint),
  (188::integer, 'While'::text, 2021::integer, true::boolean, 0::integer, null::text, null::boolean, 104::bigint),
  (189::integer, 'Thriller 25 aniversario'::text, 2008::integer, true::boolean, 12::integer, null::text, null::boolean, 105::bigint),
  (190::integer, 'Viaje a Etreum'::text, 2011::integer, true::boolean, 81::integer, null::text, null::boolean, 106::bigint),
  (191::integer, 'The Orchestral Tubular Bells'::text, 1975::integer, true::boolean, 339::integer, null::text, null::boolean, 107::bigint),
  (192::integer, 'Taste the mojo'::text, 2004::integer, true::boolean, 254::integer, null::text, null::boolean, 108::bigint),
  (193::integer, 'Dive Deep'::text, 2007::integer, true::boolean, 20::integer, null::text, null::boolean, 109::bigint),
  (194::integer, 'Fragments of freedom'::text, 2007::integer, true::boolean, 201::integer, null::text, null::boolean, 109::bigint),
  (195::integer, 'Parts of the process'::text, 2003::integer, true::boolean, 117::integer, null::text, null::boolean, 109::bigint),
  (196::integer, 'Weld'::text, 1991::integer, true::boolean, 43::integer, null::text, null::boolean, 110::bigint),
  (197::integer, 'Marchin´ Already'::text, 1997::integer, true::boolean, 337::integer, null::text, null::boolean, 111::bigint),
  (198::integer, '…en el planeta aseituna'::text, 2002::integer, true::boolean, 61::integer, null::text, null::boolean, 112::bigint),
  (199::integer, 'Cositas buenas'::text, 2004::integer, true::boolean, 196::integer, null::text, null::boolean, 113::bigint),
  (200::integer, 'dark side of the moon'::text, 1973::integer, true::boolean, 50::integer, null::text, null::boolean, 114::bigint),
  (201::integer, 'Rhinoplasty'::text, 1998::integer, true::boolean, 328::integer, null::text, null::boolean, 115::bigint),
  (202::integer, 'Planet Earth'::text, 2007::integer, true::boolean, 6::integer, null::text, null::boolean, 116::bigint),
  (203::integer, 'Queens of the stone age'::text, 1998::integer, true::boolean, 132::integer, null::text, null::boolean, 117::bigint),
  (204::integer, 'Rage Against The Machine'::text, 1992::integer, true::boolean, 19::integer, null::text, null::boolean, 118::bigint),
  (205::integer, 'Blood Sugar Sex Magik'::text, 1991::integer, true::boolean, 295::integer, null::text, null::boolean, 119::bigint),
  (206::integer, 'One Hot Minute'::text, 1995::integer, true::boolean, 327::integer, null::text, null::boolean, 119::bigint),
  (207::integer, 'Blue Moon'::text, 2002::integer, true::boolean, 673::integer, null::text, null::boolean, 120::bigint),
  (208::integer, 'Gold Collection'::text, 1990::integer, true::boolean, 296::integer, null::text, null::boolean, 121::bigint),
  (209::integer, 'At last'::text, 2003::integer, true::boolean, 161::integer, null::text, null::boolean, 122::bigint),
  (210::integer, 'off the record'::text, 2001::integer, true::boolean, 708::integer, null::text, null::boolean, 122::bigint),
  (211::integer, 'Greatest Hits'::text, 1995::integer, true::boolean, 489::integer, null::text, null::boolean, 123::bigint),
  (212::integer, 'Rock And Roll'::text, 2003::integer, true::boolean, 76::integer, null::text, null::boolean, 124::bigint),
  (213::integer, 'never mind the bollocks'::text, 1977::integer, true::boolean, 75::integer, null::text, null::boolean, 125::bigint),
  (214::integer, 'Break the cycle'::text, 2001::integer, true::boolean, 574::integer, null::text, null::boolean, 126::bigint),
  (215::integer, 'Alive In An Ultra World'::text, 2001::integer, true::boolean, 607::integer, null::text, null::boolean, 127::bigint),
  (216::integer, 'The Sky Is Crying'::text, 1991::integer, true::boolean, 386::integer, null::text, null::boolean, 128::bigint),
  (217::integer, 'Amorica'::text, 1994::integer, true::boolean, 428::integer, null::text, null::boolean, 129::bigint),
  (218::integer, 'Before the frost'::text, 2009::integer, true::boolean, 58::integer, null::text, null::boolean, 129::bigint),
  (219::integer, 'croweology'::text, 2010::integer, true::boolean, 71::integer, null::text, null::boolean, 129::bigint),
  (220::integer, 'Shake your money maker'::text, 1990::integer, true::boolean, 38::integer, null::text, null::boolean, 129::bigint),
  (221::integer, 'The southern harmony and musical companion'::text, 1992::integer, true::boolean, 668::integer, null::text, null::boolean, 129::bigint),
  (222::integer, 'Three snakes and one charm'::text, 1996::integer, true::boolean, 37::integer, null::text, null::boolean, 129::bigint),
  (223::integer, 'London Calling'::text, 1979::integer, true::boolean, 64::integer, null::text, null::boolean, 130::bigint),
  (224::integer, 'Beyond Good And Evil'::text, 2001::integer, true::boolean, 562::integer, null::text, null::boolean, 131::bigint),
  (225::integer, 'Ceremony'::text, 1991::integer, true::boolean, 92::integer, null::text, null::boolean, 131::bigint),
  (226::integer, 'Sonic Temple'::text, 1989::integer, true::boolean, 298::integer, null::text, null::boolean, 131::bigint),
  (227::integer, 'Sundazed'::text, 1969::integer, false::boolean, 115::integer, null::text, null::boolean, 132::bigint),
  (228::integer, 'Reggatta de blanc'::text, 1979::integer, true::boolean, 23::integer, null::text, null::boolean, 133::bigint),
  (229::integer, 'Greatest Hits'::text, 2000::integer, true::boolean, 62::integer, null::text, null::boolean, 134::bigint),
  (230::integer, 'Live Volumes'::text, 2004::integer, true::boolean, 259::integer, null::text, null::boolean, 135::bigint),
  (231::integer, 'Urban Hymns'::text, 1997::integer, true::boolean, 317::integer, null::text, null::boolean, 136::bigint),
  (232::integer, 'Beautiful maladies'::text, 1998::integer, true::boolean, 63::integer, null::text, null::boolean, 137::bigint),
  (233::integer, 'Drops of Jupiter'::text, 2001::integer, true::boolean, 603::integer, null::text, null::boolean, 138::bigint),
  (234::integer, 'How to dismantle an atomic bomb'::text, 2004::integer, true::boolean, 101::integer, null::text, null::boolean, 139::bigint),
  (235::integer, 'Broadway & 52nd'::text, 1997::integer, true::boolean, 53::integer, null::text, null::boolean, 140::bigint),
  (236::integer, '1984'::text, 1983::integer, true::boolean, 302::integer, null::text, null::boolean, 141::bigint),
  (237::integer, '5150'::text, 1986::integer, true::boolean, 303::integer, null::text, null::boolean, 141::bigint),
  (238::integer, 'Balance'::text, 1995::integer, true::boolean, 304::integer, null::text, null::boolean, 141::bigint),
  (239::integer, 'Diver Down'::text, 1982::integer, true::boolean, 305::integer, null::text, null::boolean, 141::bigint),
  (240::integer, 'Fair Warning'::text, 1981::integer, true::boolean, 306::integer, null::text, null::boolean, 141::bigint),
  (241::integer, 'Van Halen'::text, 1978::integer, true::boolean, 331::integer, null::text, null::boolean, 141::bigint),
  (242::integer, 'Women And Children First'::text, 1980::integer, true::boolean, 311::integer, null::text, null::boolean, 141::bigint),
  (243::integer, 'Alligator Records'::text, 2006::integer, false::boolean, 8::integer, null::text, null::boolean, 142::bigint),
  (244::integer, 'Greatest Hits'::text, 1994::integer, true::boolean, 67::integer, null::text, null::boolean, 143::bigint),
  (245::integer, 'Wolfmother'::text, 2006::integer, true::boolean, 49::integer, null::text, null::boolean, 144::bigint),
  (246::integer, '2t'::text, 2011::integer, false::boolean, 87::integer, null::text, null::boolean, 145::bigint),
  (247::integer, 'WOP(Maxi)'::text, 2011::integer, false::boolean, 79::integer, null::text, null::boolean, 145::bigint),
  (248::integer, 'Eliminator'::text, 1983::integer, true::boolean, 322::integer, null::text, null::boolean, 146::bigint),
  (249::integer, 'Tres Hombres'::text, 1973::integer, true::boolean, 27::integer, null::text, null::boolean, 146::bigint),
  (250::integer, 'Fandango'::text, 1975::integer, true::boolean, 27::integer, null::text, null::boolean, 146::bigint),
  (251::integer, 'Blue'::text, 1998::integer, true::boolean, 583::integer, null::text, null::boolean, 150::bigint),
  (252::integer, '19'::text, 2008::integer, true::boolean, 587::integer, null::text, null::boolean, 12::bigint),
  (253::integer, 'Black Holes & Revelations'::text, 2006::integer, true::boolean, 578::integer, null::text, null::boolean, 149::bigint),
  (254::integer, 'The Will to live'::text, 1997::integer, true::boolean, 581::integer, null::text, null::boolean, 20::bigint),
  (255::integer, 'Reality Bites B.S.O'::text, 1994::integer, true::boolean, 586::integer, null::text, null::boolean, 142::bigint),
  (257::integer, 'The Velvet Underground'::text, 1996::integer, true::boolean, 585::integer, null::text, null::boolean, 148::bigint),
  (258::integer, 'El último concierto'::text, 1997::integer, true::boolean, 341::integer, null::text, null::boolean, 147::bigint),
  (260::integer, 'María'::text, 2002::integer, true::boolean, 0::integer, null::text, null::boolean, 151::bigint),
  (261::integer, 'Diamond Life'::text, 1984::integer, true::boolean, 0::integer, null::text, null::boolean, 152::bigint),
  (262::integer, 'Rojo Nieve'::text, 2013::integer, true::boolean, 0::integer, null::text, null::boolean, 153::bigint),
  (263::integer, 'King Animal'::text, 2012::integer, true::boolean, 0::integer, null::text, null::boolean, 154::bigint),
  (264::integer, 'Semilla del silencio'::text, 2001::integer, true::boolean, 0::integer, null::text, null::boolean, 155::bigint),
  (265::integer, 'Picture book'::text, 1985::integer, true::boolean, 0::integer, null::text, null::boolean, 150::bigint),
  (266::integer, 'A bew flame'::text, 1989::integer, true::boolean, 0::integer, null::text, null::boolean, 150::bigint)
)
insert into public.cds (
  id,
  titulo,
  year_publicacion,
  is_in_spotify,
  etiqueta,
  caratula,
  firmado,
  grupo_id
)
select
  id,
  titulo,
  year_publicacion,
  is_in_spotify,
  etiqueta,
  caratula,
  firmado,
  grupo_id
from source
on conflict (id) do update
set
  titulo = excluded.titulo,
  year_publicacion = excluded.year_publicacion,
  is_in_spotify = excluded.is_in_spotify,
  etiqueta = excluded.etiqueta,
  caratula = excluded.caratula,
  firmado = excluded.firmado,
  grupo_id = excluded.grupo_id;

select setval(
  pg_get_serial_sequence('public.cds', 'id'),
  coalesce((select max(id) from public.cds), 1),
  true
);

commit;
