create table if not exists public.conciertos (
  id integer generated by default as identity primary key,
  fecha date not null,
  sala text,
  ciudad text,
  grupo_id bigint references public.grupos(id) on delete set null,
  festival boolean not null default false,
  fotos boolean not null default false,
  entrada text,
  descripcion text,
  cartel text,
  cronica text,
  videos text[] not null default '{}',
  videos_instagram text[] not null default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists conciertos_fecha_idx on public.conciertos (fecha desc);
create index if not exists conciertos_grupo_id_idx on public.conciertos (grupo_id);
create index if not exists conciertos_ciudad_idx on public.conciertos (ciudad);

drop trigger if exists set_conciertos_updated_at on public.conciertos;

create trigger set_conciertos_updated_at
before update on public.conciertos
for each row
execute function public.handle_updated_at();

alter table public.conciertos enable row level security;

drop policy if exists "Public can read conciertos" on public.conciertos;

create policy "Public can read conciertos"
on public.conciertos
for select
using (true);

grant select on public.conciertos to anon, authenticated;
grant all on public.conciertos to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'fotos_concierto_id_fkey'
  ) then
    alter table public.fotos
      add constraint fotos_concierto_id_fkey
      foreign key (concierto_id)
      references public.conciertos(id)
      on delete set null;
  end if;
end
$$;
