create table if not exists public.vinilos (
  id integer generated by default as identity primary key,
  titulo text not null,
  year_publicacion integer,
  caratula text,
  grupo_id bigint references public.grupos(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint vinilos_titulo_not_blank check (char_length(btrim(titulo)) > 0),
  constraint vinilos_year_publicacion_valid check (
    year_publicacion is null or year_publicacion between 1900 and 2100
  )
);

create index if not exists vinilos_titulo_idx on public.vinilos (titulo);
create index if not exists vinilos_grupo_id_idx on public.vinilos (grupo_id);
create index if not exists vinilos_year_publicacion_idx on public.vinilos (year_publicacion);

drop trigger if exists set_vinilos_updated_at on public.vinilos;

create trigger set_vinilos_updated_at
before update on public.vinilos
for each row
execute function public.handle_updated_at();

alter table public.vinilos enable row level security;

drop policy if exists "Public can read vinilos" on public.vinilos;

create policy "Public can read vinilos"
on public.vinilos
for select
using (true);

grant select on public.vinilos to anon, authenticated;
grant all on public.vinilos to service_role;
