create table if not exists public.cds (
  id integer generated by default as identity primary key,
  titulo text not null,
  year_publicacion integer,
  is_in_spotify boolean,
  etiqueta integer not null,
  caratula text,
  firmado boolean,
  grupo_id bigint not null references public.grupos(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cds_titulo_not_blank check (char_length(btrim(titulo)) > 0),
  constraint cds_year_publicacion_valid check (
    year_publicacion is null or year_publicacion between 1900 and 2100
  )
);

create index if not exists cds_titulo_idx on public.cds (titulo);
create index if not exists cds_grupo_id_idx on public.cds (grupo_id);
create index if not exists cds_etiqueta_idx on public.cds (etiqueta);
create index if not exists cds_year_publicacion_idx on public.cds (year_publicacion);

drop trigger if exists set_cds_updated_at on public.cds;

create trigger set_cds_updated_at
before update on public.cds
for each row
execute function public.handle_updated_at();

alter table public.cds enable row level security;

drop policy if exists "Public can read cds" on public.cds;

create policy "Public can read cds"
on public.cds
for select
using (true);

grant select on public.cds to anon, authenticated;
grant all on public.cds to service_role;
