create table if not exists public.discos (
  id integer generated by default as identity primary key,
  nombre text not null,
  year_publicacion integer not null,
  caratula text not null,
  discografica text not null,
  productor text not null,
  grupo_id bigint not null references public.grupos(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint discos_nombre_not_blank check (char_length(btrim(nombre)) > 0),
  constraint discos_caratula_not_blank check (char_length(btrim(caratula)) > 0),
  constraint discos_discografica_not_blank check (
    char_length(btrim(discografica)) > 0
  ),
  constraint discos_productor_not_blank check (
    char_length(btrim(productor)) > 0
  ),
  constraint discos_year_publicacion_valid check (
    year_publicacion between 1900 and 2100
  )
);

create index if not exists discos_nombre_idx on public.discos (nombre);
create index if not exists discos_grupo_id_idx on public.discos (grupo_id);
create index if not exists discos_year_publicacion_idx on public.discos (year_publicacion);
create index if not exists discos_discografica_idx on public.discos (discografica);

drop trigger if exists set_discos_updated_at on public.discos;

create trigger set_discos_updated_at
before update on public.discos
for each row
execute function public.handle_updated_at();

alter table public.discos enable row level security;

drop policy if exists "Public can read discos" on public.discos;

create policy "Public can read discos"
on public.discos
for select
using (true);

grant select on public.discos to anon, authenticated;
grant all on public.discos to service_role;
