create table if not exists public.temas (
  id integer generated by default as identity primary key,
  grupo_id bigint not null references public.grupos(id) on delete restrict,
  nombre text not null,
  observaciones text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint temas_nombre_not_blank check (char_length(btrim(nombre)) > 0)
);

create table if not exists public.videos_temas (
  id integer generated by default as identity primary key,
  tema_id integer not null references public.temas(id) on delete cascade,
  enlace text not null,
  observaciones text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint videos_temas_enlace_not_blank check (char_length(btrim(enlace)) > 0)
);

create index if not exists temas_grupo_id_idx on public.temas (grupo_id);
create index if not exists temas_nombre_idx on public.temas (nombre);
create index if not exists videos_temas_tema_id_idx on public.videos_temas (tema_id);

drop trigger if exists set_temas_updated_at on public.temas;

create trigger set_temas_updated_at
before update on public.temas
for each row
execute function public.handle_updated_at();

drop trigger if exists set_videos_temas_updated_at on public.videos_temas;

create trigger set_videos_temas_updated_at
before update on public.videos_temas
for each row
execute function public.handle_updated_at();

alter table public.temas enable row level security;
alter table public.videos_temas enable row level security;

drop policy if exists "Public can read temas" on public.temas;
drop policy if exists "Public can read videos_temas" on public.videos_temas;

create policy "Public can read temas"
on public.temas
for select
using (true);

create policy "Public can read videos_temas"
on public.videos_temas
for select
using (true);

grant select on public.temas to anon, authenticated;
grant all on public.temas to service_role;
grant select on public.videos_temas to anon, authenticated;
grant all on public.videos_temas to service_role;
