create table if not exists public.spotify_playlists_cache (
  id bigint generated by default as identity primary key,
  spotify_id text not null unique,
  name text not null,
  description text,
  image_url text,
  external_url text not null,
  owner_spotify_id text not null,
  owner_name text,
  track_count integer not null default 0,
  visibility_label text,
  collaborative boolean not null default false,
  snapshot_id text not null,
  is_active boolean not null default true,
  last_synced_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint spotify_playlists_cache_spotify_id_not_blank check (
    char_length(btrim(spotify_id)) > 0
  ),
  constraint spotify_playlists_cache_name_not_blank check (
    char_length(btrim(name)) > 0
  ),
  constraint spotify_playlists_cache_description_not_blank check (
    description is null or char_length(btrim(description)) > 0
  ),
  constraint spotify_playlists_cache_image_url_not_blank check (
    image_url is null or char_length(btrim(image_url)) > 0
  ),
  constraint spotify_playlists_cache_external_url_not_blank check (
    char_length(btrim(external_url)) > 0
  ),
  constraint spotify_playlists_cache_owner_spotify_id_not_blank check (
    char_length(btrim(owner_spotify_id)) > 0
  ),
  constraint spotify_playlists_cache_owner_name_not_blank check (
    owner_name is null or char_length(btrim(owner_name)) > 0
  ),
  constraint spotify_playlists_cache_visibility_label_not_blank check (
    visibility_label is null or char_length(btrim(visibility_label)) > 0
  ),
  constraint spotify_playlists_cache_snapshot_id_not_blank check (
    char_length(btrim(snapshot_id)) > 0
  ),
  constraint spotify_playlists_cache_track_count_valid check (
    track_count >= 0
  )
);

create table if not exists public.spotify_playlist_tracks_cache (
  id bigint generated by default as identity primary key,
  playlist_cache_id bigint not null references public.spotify_playlists_cache(id) on delete cascade,
  spotify_track_id text,
  position integer not null,
  name text not null,
  artists_label text not null,
  album_name text,
  album_release_date text,
  duration_ms bigint,
  is_local boolean not null default false,
  normalized_track_name text not null,
  canonical_track_name text not null,
  last_synced_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint spotify_playlist_tracks_cache_position_valid check (
    position > 0
  ),
  constraint spotify_playlist_tracks_cache_spotify_track_id_not_blank check (
    spotify_track_id is null or char_length(btrim(spotify_track_id)) > 0
  ),
  constraint spotify_playlist_tracks_cache_name_not_blank check (
    char_length(btrim(name)) > 0
  ),
  constraint spotify_playlist_tracks_cache_artists_label_not_blank check (
    char_length(btrim(artists_label)) > 0
  ),
  constraint spotify_playlist_tracks_cache_album_name_not_blank check (
    album_name is null or char_length(btrim(album_name)) > 0
  ),
  constraint spotify_playlist_tracks_cache_album_release_date_not_blank check (
    album_release_date is null or char_length(btrim(album_release_date)) > 0
  ),
  constraint spotify_playlist_tracks_cache_duration_ms_valid check (
    duration_ms is null or duration_ms >= 0
  ),
  constraint spotify_playlist_tracks_cache_normalized_track_name_not_blank check (
    char_length(btrim(normalized_track_name)) > 0
  ),
  constraint spotify_playlist_tracks_cache_canonical_track_name_not_blank check (
    char_length(btrim(canonical_track_name)) > 0
  )
);

create index if not exists spotify_playlists_cache_name_idx
on public.spotify_playlists_cache (name);

create index if not exists spotify_playlists_cache_owner_spotify_id_idx
on public.spotify_playlists_cache (owner_spotify_id);

create index if not exists spotify_playlists_cache_is_active_idx
on public.spotify_playlists_cache (is_active);

create index if not exists spotify_playlists_cache_last_synced_at_idx
on public.spotify_playlists_cache (last_synced_at);

create index if not exists spotify_playlist_tracks_cache_playlist_cache_id_idx
on public.spotify_playlist_tracks_cache (playlist_cache_id);

create unique index if not exists spotify_playlist_tracks_cache_playlist_position_idx
on public.spotify_playlist_tracks_cache (playlist_cache_id, position);

create unique index if not exists spotify_playlist_tracks_cache_playlist_track_idx
on public.spotify_playlist_tracks_cache (playlist_cache_id, spotify_track_id)
where spotify_track_id is not null;

create index if not exists spotify_playlist_tracks_cache_spotify_track_id_idx
on public.spotify_playlist_tracks_cache (spotify_track_id);

create index if not exists spotify_playlist_tracks_cache_name_idx
on public.spotify_playlist_tracks_cache (name);

create index if not exists spotify_playlist_tracks_cache_artists_label_idx
on public.spotify_playlist_tracks_cache (artists_label);

create index if not exists spotify_playlist_tracks_cache_normalized_track_name_idx
on public.spotify_playlist_tracks_cache (normalized_track_name);

create index if not exists spotify_playlist_tracks_cache_canonical_track_name_idx
on public.spotify_playlist_tracks_cache (canonical_track_name);

create index if not exists spotify_playlist_tracks_cache_last_synced_at_idx
on public.spotify_playlist_tracks_cache (last_synced_at);

drop trigger if exists set_spotify_playlists_cache_updated_at
on public.spotify_playlists_cache;

create trigger set_spotify_playlists_cache_updated_at
before update on public.spotify_playlists_cache
for each row
execute function public.handle_updated_at();

drop trigger if exists set_spotify_playlist_tracks_cache_updated_at
on public.spotify_playlist_tracks_cache;

create trigger set_spotify_playlist_tracks_cache_updated_at
before update on public.spotify_playlist_tracks_cache
for each row
execute function public.handle_updated_at();

alter table public.spotify_playlists_cache enable row level security;
alter table public.spotify_playlist_tracks_cache enable row level security;

drop policy if exists "Public can read spotify_playlists_cache"
on public.spotify_playlists_cache;

drop policy if exists "Public can read spotify_playlist_tracks_cache"
on public.spotify_playlist_tracks_cache;

create policy "Public can read spotify_playlists_cache"
on public.spotify_playlists_cache
for select
using (true);

create policy "Public can read spotify_playlist_tracks_cache"
on public.spotify_playlist_tracks_cache
for select
using (true);

grant select on public.spotify_playlists_cache to anon, authenticated;
grant all on public.spotify_playlists_cache to service_role;

grant select on public.spotify_playlist_tracks_cache to anon, authenticated;
grant all on public.spotify_playlist_tracks_cache to service_role;
