create table if not exists public.libros (
  id integer generated by default as identity primary key,
  titulo text not null,
  categoria text,
  autor text,
  isbn text,
  caratula text,
  enlace text,
  deposito_legal text,
  editorial text,
  protagonista text,
  sinopsis text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists libros_titulo_idx on public.libros (titulo);
create index if not exists libros_categoria_idx on public.libros (categoria);
create index if not exists libros_protagonista_idx on public.libros (protagonista);

drop trigger if exists set_libros_updated_at on public.libros;

create trigger set_libros_updated_at
before update on public.libros
for each row
execute function public.handle_updated_at();

alter table public.libros enable row level security;

drop policy if exists "Public can read libros" on public.libros;

create policy "Public can read libros"
on public.libros
for select
using (true);

grant select on public.libros to anon, authenticated;
grant all on public.libros to service_role;
