create table if not exists public.youtube_video_matches (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  track_name text not null,
  artists_label text not null,
  album_name text,
  album_release_year text,
  matched_query text,
  has_match boolean not null default false,
  video_id text,
  title text,
  channel_title text,
  description text,
  thumbnail_url text,
  external_url text,
  embed_url text,
  view_count bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint youtube_video_matches_cache_key_not_blank check (char_length(btrim(cache_key)) > 0),
  constraint youtube_video_matches_track_name_not_blank check (char_length(btrim(track_name)) > 0),
  constraint youtube_video_matches_artists_label_not_blank check (char_length(btrim(artists_label)) > 0)
);

create index if not exists youtube_video_matches_track_name_idx
on public.youtube_video_matches (track_name);

create index if not exists youtube_video_matches_artists_label_idx
on public.youtube_video_matches (artists_label);

drop trigger if exists set_youtube_video_matches_updated_at on public.youtube_video_matches;

create trigger set_youtube_video_matches_updated_at
before update on public.youtube_video_matches
for each row
execute function public.handle_updated_at();

alter table public.youtube_video_matches enable row level security;

drop policy if exists "Public can read youtube_video_matches"
on public.youtube_video_matches;

create policy "Public can read youtube_video_matches"
on public.youtube_video_matches
for select
using (true);

grant select on public.youtube_video_matches to anon, authenticated;
grant all on public.youtube_video_matches to service_role;
