create table if not exists public.videos (
  id integer generated by default as identity primary key,
  imagen text,
  enlace text not null,
  texto text not null,
  categoria text,
  plataforma text,
  info text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists videos_texto_idx on public.videos (texto);
create index if not exists videos_categoria_idx on public.videos (categoria);
create index if not exists videos_plataforma_idx on public.videos (plataforma);

drop trigger if exists set_videos_updated_at on public.videos;

create trigger set_videos_updated_at
before update on public.videos
for each row execute function public.handle_updated_at();

alter table public.videos enable row level security;

drop policy if exists "Public can read videos" on public.videos;

create policy "Public can read videos"
on public.videos
for select
using (true);

grant select on public.videos to anon, authenticated;
grant all on public.videos to service_role;
